#!/usr/bin/env python3
"""
Synthesize JEDEC SPD blobs for AxlSpd codec unit tests.

Outputs:
  spd-ddr4-micron-8gb.bin   — 256 bytes, DDR4 UDIMM, x8, single-rank, ECC, DDR4-2400
                              Lower-page only (QEMU's smbus-eeprom is 256 bytes
                              and does not model the EE1004 SPA mechanism).
  spd-ddr5-samsung-16gb.bin — 1024 bytes, DDR5 UDIMM, x8, single-rank, ECC, DDR5-4800
                              Full payload (decoded directly via axl_spd_decode;
                              no SPD5118 hub model in QEMU yet).

These are not byte-perfect captures of real DIMMs — they're crafted to
exercise specific decoder paths. Re-run when adding new decode coverage.
"""
from __future__ import annotations

from pathlib import Path


def make_ddr4_micron_8gb() -> bytes:
    spd = bytearray(256)
    spd[0]   = 0x12                  # bytes_used=256, bytes_total=512
    spd[1]   = 0x10                  # SPD revision 1.0
    spd[2]   = 0x0C                  # key byte: DDR4
    spd[3]   = 0x02                  # module type: UDIMM
    spd[4]   = 0x05                  # density code 5 = 8 Gb
    spd[12]  = 0x01                  # ranks=1, device width = x8
    spd[13]  = 0x0B                  # 64-bit primary + 8-bit ECC extension
    spd[18]  = 7                     # tCK_min in MTB (0.125 ns) = 875 ps
    spd[125] = 0xD6                  # FTB correction = -42 ps -> total 833 ps
    return bytes(spd)


def make_ddr5_samsung_16gb() -> bytes:
    spd = bytearray(1024)
    spd[0]    = 0x30                 # bytes_used / total markers
    spd[1]    = 0x10
    spd[2]    = 0x12                 # key byte 0: DDR5
    spd[3]    = 0x02                 # module type: UDIMM
    spd[4]    = 0x04                 # density code 4 = 16 Gb (= 2 GiB per device)
    spd[6]    = 0x01                 # SDRAM I/O width: x8 (low 3 bits = 001)
    spd[0x14] = 0xA0                 # tCK low  (0x01A0 = 416 ps -> ~4800 MT/s)
    spd[0x15] = 0x01                 # tCK high
    spd[0xEB] = 0x0B                 # bus width: 64-bit primary (low 3 = 011) + ECC ext (bit 3)
    # Capacity = 2 GiB/device × (64 / 8) = 16 GiB
    # Module manufacturing info (offset 512+):
    spd[512] = 0x00                  # Samsung: bank 0, id 0xCE
    spd[513] = 0xCE
    spd[514] = 0x01                  # location code
    spd[515] = 0x25                  # year BCD = 25 -> 2025
    spd[516] = 0x12                  # week BCD = 12
    spd[517:521] = b'\xDE\xAD\xBE\xEF'
    part_number = b'M323R2GA3BB0-CWMOD'           # 18 chars
    spd[521:521 + len(part_number)] = part_number
    # Pad remainder of part-number field with 0x20 (ASCII space) — gets trimmed.
    for i in range(521 + len(part_number), 521 + 30):
        spd[i] = 0x20
    spd[552] = 0x00                  # DRAM mfg: same as module
    spd[553] = 0xCE
    return bytes(spd)


def write_c_array(path: Path, name: str, blob: bytes) -> None:
    lines: list[str] = [
        '/* SPDX-License-Identifier: Apache-2.0 */',
        '/* Copyright 2026 AximCode */',
        '/* AUTO-GENERATED by test/data/gen-spd.py — do not edit by hand. */',
        '',
        '#include <stddef.h>',
        '#include <stdint.h>',
        '',
        f'static const uint8_t {name}[{len(blob)}] = {{',
    ]
    for i in range(0, len(blob), 12):
        chunk = ', '.join(f'0x{b:02X}' for b in blob[i:i + 12])
        lines.append(f'    {chunk},')
    lines.append('};')
    lines.append('')
    path.write_text('\n'.join(lines))


def main() -> None:
    # QEMU's memory-backend-file rounds size= up to host page size (4096
    # on x86_64). Pad each .bin to the page size so smbus-eeprom's
    # memdev= link can mmap it without "backing store too small". The
    # smbus-eeprom device only consumes the first SMBUS_EEPROM_SIZE
    # (256) bytes; the rest is harmless padding. The .h C-array variants
    # stay at the natural SPD size — they're for the in-binary decoder
    # unit tests and never see QEMU.
    page_size = 4096
    out_dir = Path(__file__).resolve().parent
    ddr4 = make_ddr4_micron_8gb()
    ddr5 = make_ddr5_samsung_16gb()
    ddr4_padded = ddr4 + b'\x00' * (page_size - len(ddr4))
    ddr5_padded = ddr5 + b'\x00' * ((page_size - len(ddr5) % page_size) % page_size)
    (out_dir / 'spd-ddr4-micron-8gb.bin').write_bytes(ddr4_padded)
    (out_dir / 'spd-ddr5-samsung-16gb.bin').write_bytes(ddr5_padded)
    write_c_array(out_dir / 'spd-ddr4-micron-8gb.h', 'kSpdDdr4Micron8Gb', ddr4)
    write_c_array(out_dir / 'spd-ddr5-samsung-16gb.h', 'kSpdDdr5Samsung16Gb', ddr5)
    print(f'Wrote SPD blobs (.bin padded to {page_size} bytes, .h natural) into {out_dir}')


if __name__ == '__main__':
    main()
