#!/usr/bin/env python3
"""Generate the JSONTestSuite conformance corpus as a C header.

AXL's unit tests run in QEMU with no filesystem, so the RFC 8259
conformance corpus has to be compiled in rather than read from disk.
This turns nst/JSONTestSuite's ``test_parsing/`` directory into
``test/unit/axl-json-corpus.h``: one byte array per document plus an
index table carrying the file name and its expected-outcome class.

The class is the file-name prefix JSONTestSuite defines:

    y_   must be ACCEPTED by an RFC 8259 parser
    n_   must be REJECTED
    i_   implementation-defined; RFC 8259 leaves it free

Documents are emitted as byte arrays, not C string literals, on
purpose: the corpus deliberately contains embedded NULs, raw control
characters and ill-formed UTF-8, none of which survive a string
literal, and the repo's ``make check-ascii`` gate requires the
generated source itself stay pure ASCII.

Two files are held back because they are recursion bombs measured in
hundreds of kilobytes (100000 nested arrays, 50000 nested objects).
They are regenerated at runtime by the test instead. The header carries
their names in ``json_corpus_skipped[]`` plus a
``AXL_JSON_CORPUS_SKIPPED_COUNT``, and the test asserts it rebuilds one
document per entry -- so a case that grows past SKIP_OVERSIZE cannot
quietly vanish from the sweep.

Usage:
    python3 scripts/generate-json-corpus.py [--fetch]
    python3 scripts/generate-json-corpus.py --input DIR --output FILE
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

UPSTREAM = "https://github.com/nst/JSONTestSuite"

DEFAULT_DEPS = Path("deps/jsontestsuite")
DEFAULT_OUTPUT = Path("test/unit/axl-json-corpus.h")

# Bytes above which a document is left out of the header and rebuilt at
# runtime by the test. Every corpus file except the two recursion bombs
# is well under 2 KB.
SKIP_OVERSIZE = 2048

BYTES_PER_LINE = 16


def fetch(dest: Path) -> None:
    """Shallow-clone JSONTestSuite into @dest if it is not there yet."""
    if (dest / "test_parsing").is_dir():
        print(f"  corpus already present: {dest}")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    print(f"  cloning {UPSTREAM} -> {dest}")
    subprocess.run(
        ["git", "clone", "--depth", "1", "--quiet", UPSTREAM, str(dest)],
        check=True,
    )


def c_ident(index: int) -> str:
    """Identifier fragment for the case at @index.

    Deliberately the index and not the file name. Mapping the name's
    punctuation to underscores collides -- ``n_number_1.0e+`` and
    ``n_number_1.0e-`` both become ``n_number_1_0e_`` -- and a
    redefinition of a corpus array is a build break with a cause that
    reads nothing like "two test files differ only in punctuation". The
    name rides along in a comment and in the index table.
    """
    return f"{index:03d}"


def emit_bytes(data: bytes) -> list[str]:
    """Format @data as indented C initializer lines."""
    lines: list[str] = []
    for off in range(0, len(data), BYTES_PER_LINE):
        chunk = data[off:off + BYTES_PER_LINE]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    return lines


def generate(input_dir: Path, output: Path, upstream_rev: str) -> int:
    parsing = input_dir / "test_parsing"
    if not parsing.is_dir():
        print(f"error: {parsing} not found (run with --fetch)", file=sys.stderr)
        return 1

    files = sorted(parsing.glob("*.json"), key=lambda p: p.name)
    if not files:
        print(f"error: no .json files under {parsing}", file=sys.stderr)
        return 1

    kept: list[tuple[str, str, bytes]] = []
    skipped: list[tuple[str, int]] = []
    for path in files:
        name = path.stem
        cls = name[0]
        if cls not in ("y", "n", "i") or not name[1:2] == "_":
            print(f"error: {path.name} has no y_/n_/i_ prefix", file=sys.stderr)
            return 1
        data = path.read_bytes()
        if len(data) > SKIP_OVERSIZE:
            skipped.append((name, len(data)))
            continue
        kept.append((name, cls, data))

    out: list[str] = []
    add = out.append
    add("/* SPDX-License-Identifier: Apache-2.0 */")
    add("/* Copyright 2026 AximCode */")
    add("")
    add("/** @file axl-json-corpus.h")
    add("    GENERATED by scripts/generate-json-corpus.py -- do not edit.")
    add("")
    add(f"    Source: {UPSTREAM}")
    add(f"    Revision: {upstream_rev}")
    add("    License: MIT (Nicolas Seriot). Compatible with Apache-2.0;")
    add("    see deps/jsontestsuite/LICENSE in a fetched tree.")
    add("")
    add("    The RFC 8259 conformance corpus from \"Parsing JSON is a")
    add("    Minefield\". File-name prefixes are the expected outcome:")
    add("    y_ must be accepted, n_ must be rejected, i_ is left free by")
    add("    the standard.")
    add("")
    add(f"    Cases embedded: {len(kept)}")
    if skipped:
        add(f"    Cases HELD BACK as oversize (> {SKIP_OVERSIZE} bytes), each a")
        add("    nesting bomb the test rebuilds at runtime instead:")
        for name, size in skipped:
            add(f"      {name} ({size} bytes)")
    add("**/")
    add("")
    add("#ifndef AXL_JSON_CORPUS_H")
    add("#define AXL_JSON_CORPUS_H")
    add("")
    add("#include <stddef.h>")
    add("")
    add("/** One conformance case: the document bytes and what must happen. */")
    add("typedef struct {")
    add("    const char          *name;   ///< corpus file name, without .json")
    add("    char                 cls;    ///< 'y' accept, 'n' reject, 'i' free")
    add("    const unsigned char *bytes;  ///< document bytes (may contain NUL)")
    add("    size_t               len;    ///< byte count")
    add("} AxlJsonCorpusCase;")
    add("")

    for index, (name, _cls, data) in enumerate(kept):
        add(f"/* {name} */")
        add(f"static const unsigned char json_corpus_{c_ident(index)}[] = {{")
        out.extend(emit_bytes(data))
        add("};")
    add("")

    add("static const AxlJsonCorpusCase json_corpus[] = {")
    for index, (name, cls, _data) in enumerate(kept):
        ident = c_ident(index)
        add(f'    {{ "{name}", \'{cls}\', json_corpus_{ident},'
            f' sizeof(json_corpus_{ident}) }},')
    add("};")
    add("")
    add("/** Cases HELD BACK as oversize, by name.")
    add(" *")
    add(" * A checkable table, not just the prose in the file comment above:")
    add(" * the test matches every name here against the documents it rebuilds")
    add(" * at runtime, so a corpus case that grows past the size threshold")
    add(" * cannot quietly drop out of the sweep. Growing this list has to be")
    add(" * a deliberate act with a matching reconstruction. */")
    add("static const char *const json_corpus_skipped[] = {")
    for name, _size in skipped:
        add(f'    "{name}",')
    if not skipped:
        add("    NULL,  /* none held back at this threshold */")
    add("};")
    add("")
    add("/// Number of held-back cases the test must rebuild itself.")
    add(f"#define AXL_JSON_CORPUS_SKIPPED_COUNT {len(skipped)}")
    add("")
    add("/// Number of embedded conformance cases.")
    add("#define AXL_JSON_CORPUS_COUNT "
        "(sizeof(json_corpus) / sizeof(json_corpus[0]))")
    add("")
    counts = {c: sum(1 for _, cc, _ in kept if cc == c) for c in "yni"}
    add("/** @name Embedded case counts per class")
    add(" *")
    add(" * Spelled out so a corpus regeneration that changes the mix is a")
    add(" * visible diff in the assertions, not a silently different total.")
    add(" * @{ */")
    add(f"#define AXL_JSON_CORPUS_Y_COUNT {counts['y']}")
    add(f"#define AXL_JSON_CORPUS_N_COUNT {counts['n']}")
    add(f"#define AXL_JSON_CORPUS_I_COUNT {counts['i']}")
    add("/** @} */")
    add("")
    add("#endif /* AXL_JSON_CORPUS_H */")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out) + "\n", encoding="ascii")

    print(f"  wrote {output}")
    print(f"  embedded {len(kept)} cases "
          f"(y={counts['y']} n={counts['n']} i={counts['i']})")
    for name, size in skipped:
        print(f"  held back {name} ({size} bytes) -- rebuilt at runtime")
    return 0


def upstream_revision(repo: Path) -> str:
    try:
        rev = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        )
        return rev.stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return "unknown"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--fetch", action="store_true",
                    help="shallow-clone JSONTestSuite if absent")
    ap.add_argument("--input", type=Path, default=DEFAULT_DEPS,
                    help=f"JSONTestSuite checkout (default {DEFAULT_DEPS})")
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                    help=f"header to write (default {DEFAULT_OUTPUT})")
    args = ap.parse_args()

    if args.fetch:
        fetch(args.input)
    return generate(args.input, args.output, upstream_revision(args.input))


if __name__ == "__main__":
    sys.exit(main())
