#!/usr/bin/env python3
from __future__ import annotations

"""
Convert the canonical usb.ids text database into the JSON5 schema
that axl-sdk's axl_usb_ids_load expects.

Source format (https://www.linux-usb.org/usb.ids) — same tab-indented
hierarchy as pci.ids:

    # comments start with #
    VVVV  Vendor Name              <- column 0 — vendor
    \\tPPPP  Product Name            <- one tab — product (a.k.a. device)
    \\t\\tII  Interface Name          <- two tabs — rarely populated; we drop

USB has no subsystem dimension (no analog of PCI's `(svid, sdid)`),
so the output schema is simpler than pci-ids.json5:

    {
        schema: 1,
        vendors: [
            { id: 0x046D, name: 'Logitech, Inc.',
              devices: [
                { pid: 0xC52B, name: 'Unifying Receiver' },
              ],
            },
        ],
    }

Schema 1 IS the hierarchical layout for USB — there's no v1-vs-v2
flat/hierarchical split because there's nothing extra to flatten.

Usage:
    usb-ids-to-json5.py USB_IDS_FILE > usb-ids.json5
    usb-ids-to-json5.py --vendors-only 046d,0bda,1d6b USB_IDS_FILE
    usb-ids-to-json5.py --self-test     # exercise the parser/emitters

The full usb.ids file generates ~17000 entries. Curated subsets are
usually preferred over the full set for UEFI tools — pass
`--vendors-only` with a comma-separated list of hex vendor IDs.

The line-level parser is shared with pci-ids-to-json5.py via
scripts/_ids_parser.py.
"""

import argparse
import sys
from pathlib import Path
from typing import TextIO

from _ids_parser import (
    Device,
    ParsedIds,
    Vendor,
    parse_ids,
    quote_json5,
)


# ---------------------------------------------------------------------------
# Emitter
# ---------------------------------------------------------------------------

def _emit_hierarchical(
    vendors: list[Vendor],
    devices: list[Device],
    out: TextIO,
) -> None:
    """USB schema 1 hierarchical: vendors[] with nested devices[]."""
    devices_by_vid: dict[int, list[tuple[int, str]]] = {}
    for vid, pid, name in devices:
        devices_by_vid.setdefault(vid, []).append((pid, name))

    out.write("    schema: 1,\n")
    out.write("    vendors: [\n")
    for vid, vname in vendors:
        v_devs = devices_by_vid.get(vid, [])
        if not v_devs:
            out.write(f"        {{ id: 0x{vid:04X}, "
                      f"name: '{quote_json5(vname)}' }},\n")
            continue
        out.write(f"        {{ id: 0x{vid:04X}, "
                  f"name: '{quote_json5(vname)}',\n")
        out.write(f"          devices: [\n")
        for pid, dname in v_devs:
            out.write(f"            {{ pid: 0x{pid:04X}, "
                      f"name: '{quote_json5(dname)}' }},\n")
        out.write(f"          ],\n")
        out.write(f"        }},\n")
    out.write("    ],\n")


def emit_usb_ids(
    parsed: ParsedIds,
    out: TextIO,
) -> None:
    """Write the usb-ids.json5 document."""
    out.write("// Generated by scripts/usb-ids-to-json5.py from usb.ids.\n")
    out.write("// Numeric IDs are uncopyrightable factual data; names are\n")
    out.write("// sourced from the public usb.ids registry.\n")
    out.write("{\n")
    _emit_hierarchical(parsed.vendors, parsed.devices, out)
    out.write("}\n")


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

_SELF_TEST_INPUT = """\
# Sample usb.ids fixture for the script's --self-test mode.
046d  Logitech, Inc.
\tc077  M105 Optical Mouse
\tc52b  Unifying Receiver
\t\t01  Keyboard interface
0627  Adomax Technology Co., Ltd
\t0001  QEMU USB Mouse
0001  EmptyVendor

# List of known device classes, subclasses and protocols
C 09  Hub
\t00  Unused
\t\t00  Full speed (or root) hub
"""


def _self_test() -> int:
    import io

    parsed = parse_ids(_SELF_TEST_INPUT, has_subsystems=False)

    # Parser shape — vendors / devices populated; the third-tier
    # `\t\t01  Keyboard interface` line MUST be dropped because
    # has_subsystems=False (USB interface entries are an artifact of
    # the file format we have no consumer for).
    assert parsed.vendors == [(0x046D, "Logitech, Inc."),
                              (0x0627, "Adomax Technology Co., Ltd"),
                              (0x0001, "EmptyVendor")], parsed.vendors
    assert parsed.devices == [(0x046D, 0xC077, "M105 Optical Mouse"),
                              (0x046D, 0xC52B, "Unifying Receiver"),
                              (0x0627, 0x0001, "QEMU USB Mouse")], \
        parsed.devices
    assert parsed.subsystems == [], \
        "USB parser must drop third-tier interface rows"
    assert parsed.subsys_by_device == {}, \
        "USB parser must not populate subsys_by_device"

    # Class section is parsed (we share infrastructure with PCI) but
    # the USB frontend ignores it — there's no axl_usb_class sidecar
    # converter today. Confirm the parser still walked it cleanly.
    assert parsed.class_bases == [(0x09, "Hub")], parsed.class_bases

    # Hierarchical emit — one vendor block per ID, devices nested.
    buf = io.StringIO()
    emit_usb_ids(parsed, buf)
    out = buf.getvalue()
    assert "schema: 1" in out
    assert "id: 0x046D" in out
    assert "pid: 0xC52B" in out
    assert "name: 'Unifying Receiver'" in out
    # Vendor with no devices renders single-line.
    assert "{ id: 0x0001, name: 'EmptyVendor' }," in out, \
        f"expected single-line vendor-no-devices entry; got:\n{out}"
    # Device entry is single-line (USB has no nested subsystems).
    assert "{ pid: 0xC077, name: 'M105 Optical Mouse' }," in out

    # Vendor filter affects devices but not the vendor list itself.
    parsed_filtered = parse_ids(
        _SELF_TEST_INPUT, has_subsystems=False, allowed_vendors={0x0627})
    assert len(parsed_filtered.vendors) == 3, \
        "vendors are unfiltered (Logitech + Adomax + EmptyVendor)"
    assert len(parsed_filtered.devices) == 1 \
        and parsed_filtered.devices[0][0] == 0x0627, \
        "only Adomax devices remain after filter"

    # Cross-section regression: a top-level non-`C XX` line in the
    # class section (e.g. `AT 0100  ...` in real usb.ids) must clear
    # current_class_base so subsequent `\tYY` rows aren't
    # misattributed. Build a fixture and verify.
    cross_section = (
        "C 09  Hub\n"
        "\t00  Hub subclass\n"
        "AT 0100  USB Undefined\n"
        "\t02  This must NOT attach to class 0x09\n"
    )
    p2 = parse_ids(cross_section, has_subsystems=False)
    assert (0x09, 0x02, "This must NOT attach to class 0x09") not in p2.class_subs, \
        "class_base must clear when a non-`C XX` top-level taxonomy line appears"

    print("PASS: scripts/usb-ids-to-json5.py self-test", file=sys.stderr)
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert usb.ids → axl-sdk JSON5 schema",
    )
    parser.add_argument(
        "input", nargs="?",
        help="path to usb.ids file (or '-' for stdin); omit with --self-test",
    )
    parser.add_argument(
        "--vendors-only",
        help="comma-separated hex vendor IDs to include "
             "(e.g. 046d,0bda,1d6b). Vendors not in the list are still "
             "listed; only their devices are dropped.",
    )
    parser.add_argument(
        "-o", "--output",
        help="usb-ids.json5 output file (default: stdout)",
    )
    parser.add_argument(
        "--self-test", action="store_true",
        help="exercise the parser/emitters against an embedded fixture; "
             "exits 0 on pass, non-zero on assertion failure",
    )
    args = parser.parse_args()

    if args.self_test:
        return _self_test()
    if args.input is None:
        parser.error("input file required (or pass --self-test)")

    if args.input == "-":
        text = sys.stdin.read()
    else:
        text = Path(args.input).read_text(encoding="utf-8", errors="replace")

    allowed: set[int] | None = None
    if args.vendors_only:
        allowed = {int(v.strip(), 16)
                   for v in args.vendors_only.split(",") if v.strip()}

    parsed = parse_ids(text, has_subsystems=False, allowed_vendors=allowed)

    if args.output:
        with Path(args.output).open("w", encoding="utf-8") as f:
            emit_usb_ids(parsed, f)
    else:
        emit_usb_ids(parsed, sys.stdout)

    print(f"# usb-ids schema 1: {len(parsed.vendors)} vendors, "
          f"{len(parsed.devices)} devices",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
