/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright 2026 AximCode */

/** @file axl-json-corpus.h
    GENERATED by scripts/generate-json-corpus.py -- do not edit.

    Source: https://github.com/nst/JSONTestSuite
    Revision: 1ef36fa01286573e846ac449e8683f8833c5b26a
    License: MIT (Nicolas Seriot). Compatible with Apache-2.0;
    see deps/jsontestsuite/LICENSE in a fetched tree.

    The RFC 8259 conformance corpus from "Parsing JSON is a
    Minefield". File-name prefixes are the expected outcome:
    y_ must be accepted, n_ must be rejected, i_ is left free by
    the standard.

    Cases embedded: 316
    Cases HELD BACK as oversize (> 2048 bytes), each a
    nesting bomb the test rebuilds at runtime instead:
      n_structure_100000_opening_arrays (100000 bytes)
      n_structure_open_array_object (250001 bytes)
**/

#ifndef AXL_JSON_CORPUS_H
#define AXL_JSON_CORPUS_H

#include <stddef.h>

/** One conformance case: the document bytes and what must happen. */
typedef struct {
    const char          *name;   ///< corpus file name, without .json
    char                 cls;    ///< 'y' accept, 'n' reject, 'i' free
    const unsigned char *bytes;  ///< document bytes (may contain NUL)
    size_t               len;    ///< byte count
} AxlJsonCorpusCase;

/* i_number_double_huge_neg_exp */
static const unsigned char json_corpus_000[] = {
    0x5b, 0x31, 0x32, 0x33, 0x2e, 0x34, 0x35, 0x36, 0x65, 0x2d, 0x37, 0x38, 0x39, 0x5d,
};
/* i_number_huge_exp */
static const unsigned char json_corpus_001[] = {
    0x5b, 0x30, 0x2e, 0x34, 0x65, 0x30, 0x30, 0x36, 0x36, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x39, 0x36, 0x39, 0x39,
    0x39, 0x39, 0x39, 0x39, 0x39, 0x30, 0x30, 0x36, 0x5d,
};
/* i_number_neg_int_huge_exp */
static const unsigned char json_corpus_002[] = {
    0x5b, 0x2d, 0x31, 0x65, 0x2b, 0x39, 0x39, 0x39, 0x39, 0x5d,
};
/* i_number_pos_double_huge_exp */
static const unsigned char json_corpus_003[] = {
    0x5b, 0x31, 0x2e, 0x35, 0x65, 0x2b, 0x39, 0x39, 0x39, 0x39, 0x5d,
};
/* i_number_real_neg_overflow */
static const unsigned char json_corpus_004[] = {
    0x5b, 0x2d, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x65, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x5d,
};
/* i_number_real_pos_overflow */
static const unsigned char json_corpus_005[] = {
    0x5b, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x65, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x5d,
};
/* i_number_real_underflow */
static const unsigned char json_corpus_006[] = {
    0x5b, 0x31, 0x32, 0x33, 0x65, 0x2d, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x5d,
};
/* i_number_too_big_neg_int */
static const unsigned char json_corpus_007[] = {
    0x5b, 0x2d, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x31, 0x32,
    0x33, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33, 0x31, 0x32, 0x33,
    0x5d,
};
/* i_number_too_big_pos_int */
static const unsigned char json_corpus_008[] = {
    0x5b, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x5d,
};
/* i_number_very_big_negative_int */
static const unsigned char json_corpus_009[] = {
    0x5b, 0x2d, 0x32, 0x33, 0x37, 0x34, 0x36, 0x32, 0x33, 0x37, 0x34, 0x36, 0x37, 0x33, 0x32, 0x37,
    0x36, 0x38, 0x39, 0x34, 0x32, 0x37, 0x39, 0x38, 0x33, 0x32, 0x37, 0x34, 0x39, 0x38, 0x33, 0x32,
    0x34, 0x32, 0x33, 0x34, 0x37, 0x39, 0x38, 0x32, 0x33, 0x32, 0x34, 0x36, 0x33, 0x32, 0x37, 0x38,
    0x34, 0x36, 0x5d,
};
/* i_object_key_lone_2nd_surrogate */
static const unsigned char json_corpus_010[] = {
    0x7b, 0x22, 0x5c, 0x75, 0x44, 0x46, 0x41, 0x41, 0x22, 0x3a, 0x30, 0x7d,
};
/* i_string_1st_surrogate_but_2nd_missing */
static const unsigned char json_corpus_011[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x41, 0x44, 0x41, 0x22, 0x5d,
};
/* i_string_1st_valid_surrogate_2nd_invalid */
static const unsigned char json_corpus_012[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x38, 0x38, 0x5c, 0x75, 0x31, 0x32, 0x33, 0x34, 0x22, 0x5d,
};
/* i_string_UTF-16LE_with_BOM */
static const unsigned char json_corpus_013[] = {
    0xff, 0xfe, 0x5b, 0x00, 0x22, 0x00, 0xe9, 0x00, 0x22, 0x00, 0x5d, 0x00,
};
/* i_string_UTF-8_invalid_sequence */
static const unsigned char json_corpus_014[] = {
    0x5b, 0x22, 0xe6, 0x97, 0xa5, 0xd1, 0x88, 0xfa, 0x22, 0x5d,
};
/* i_string_UTF8_surrogate_U+D800 */
static const unsigned char json_corpus_015[] = {
    0x5b, 0x22, 0xed, 0xa0, 0x80, 0x22, 0x5d,
};
/* i_string_incomplete_surrogate_and_escape_valid */
static const unsigned char json_corpus_016[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x6e, 0x22, 0x5d,
};
/* i_string_incomplete_surrogate_pair */
static const unsigned char json_corpus_017[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x64, 0x31, 0x65, 0x61, 0x22, 0x5d,
};
/* i_string_incomplete_surrogates_escape_valid */
static const unsigned char json_corpus_018[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x6e,
    0x22, 0x5d,
};
/* i_string_invalid_lonely_surrogate */
static const unsigned char json_corpus_019[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x64, 0x38, 0x30, 0x30, 0x22, 0x5d,
};
/* i_string_invalid_surrogate */
static const unsigned char json_corpus_020[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x64, 0x38, 0x30, 0x30, 0x61, 0x62, 0x63, 0x22, 0x5d,
};
/* i_string_invalid_utf-8 */
static const unsigned char json_corpus_021[] = {
    0x5b, 0x22, 0xff, 0x22, 0x5d,
};
/* i_string_inverted_surrogates_U+1D11E */
static const unsigned char json_corpus_022[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x64, 0x31, 0x65, 0x5c, 0x75, 0x44, 0x38, 0x33, 0x34, 0x22, 0x5d,
};
/* i_string_iso_latin_1 */
static const unsigned char json_corpus_023[] = {
    0x5b, 0x22, 0xe9, 0x22, 0x5d,
};
/* i_string_lone_second_surrogate */
static const unsigned char json_corpus_024[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x46, 0x41, 0x41, 0x22, 0x5d,
};
/* i_string_lone_utf8_continuation_byte */
static const unsigned char json_corpus_025[] = {
    0x5b, 0x22, 0x81, 0x22, 0x5d,
};
/* i_string_not_in_unicode_range */
static const unsigned char json_corpus_026[] = {
    0x5b, 0x22, 0xf4, 0xbf, 0xbf, 0xbf, 0x22, 0x5d,
};
/* i_string_overlong_sequence_2_bytes */
static const unsigned char json_corpus_027[] = {
    0x5b, 0x22, 0xc0, 0xaf, 0x22, 0x5d,
};
/* i_string_overlong_sequence_6_bytes */
static const unsigned char json_corpus_028[] = {
    0x5b, 0x22, 0xfc, 0x83, 0xbf, 0xbf, 0xbf, 0xbf, 0x22, 0x5d,
};
/* i_string_overlong_sequence_6_bytes_null */
static const unsigned char json_corpus_029[] = {
    0x5b, 0x22, 0xfc, 0x80, 0x80, 0x80, 0x80, 0x80, 0x22, 0x5d,
};
/* i_string_truncated-utf-8 */
static const unsigned char json_corpus_030[] = {
    0x5b, 0x22, 0xe0, 0xff, 0x22, 0x5d,
};
/* i_string_utf16BE_no_BOM */
static const unsigned char json_corpus_031[] = {
    0x00, 0x5b, 0x00, 0x22, 0x00, 0xe9, 0x00, 0x22, 0x00, 0x5d,
};
/* i_string_utf16LE_no_BOM */
static const unsigned char json_corpus_032[] = {
    0x5b, 0x00, 0x22, 0x00, 0xe9, 0x00, 0x22, 0x00, 0x5d, 0x00,
};
/* i_structure_500_nested_arrays */
static const unsigned char json_corpus_033[] = {
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b, 0x5b,
    0x5b, 0x5b, 0x5b, 0x5b, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
    0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d, 0x5d,
};
/* i_structure_UTF-8_BOM_empty_object */
static const unsigned char json_corpus_034[] = {
    0xef, 0xbb, 0xbf, 0x7b, 0x7d,
};
/* n_array_1_true_without_comma */
static const unsigned char json_corpus_035[] = {
    0x5b, 0x31, 0x20, 0x74, 0x72, 0x75, 0x65, 0x5d,
};
/* n_array_a_invalid_utf8 */
static const unsigned char json_corpus_036[] = {
    0x5b, 0x61, 0xe5, 0x5d,
};
/* n_array_colon_instead_of_comma */
static const unsigned char json_corpus_037[] = {
    0x5b, 0x22, 0x22, 0x3a, 0x20, 0x31, 0x5d,
};
/* n_array_comma_after_close */
static const unsigned char json_corpus_038[] = {
    0x5b, 0x22, 0x22, 0x5d, 0x2c,
};
/* n_array_comma_and_number */
static const unsigned char json_corpus_039[] = {
    0x5b, 0x2c, 0x31, 0x5d,
};
/* n_array_double_comma */
static const unsigned char json_corpus_040[] = {
    0x5b, 0x31, 0x2c, 0x2c, 0x32, 0x5d,
};
/* n_array_double_extra_comma */
static const unsigned char json_corpus_041[] = {
    0x5b, 0x22, 0x78, 0x22, 0x2c, 0x2c, 0x5d,
};
/* n_array_extra_close */
static const unsigned char json_corpus_042[] = {
    0x5b, 0x22, 0x78, 0x22, 0x5d, 0x5d,
};
/* n_array_extra_comma */
static const unsigned char json_corpus_043[] = {
    0x5b, 0x22, 0x22, 0x2c, 0x5d,
};
/* n_array_incomplete */
static const unsigned char json_corpus_044[] = {
    0x5b, 0x22, 0x78, 0x22,
};
/* n_array_incomplete_invalid_value */
static const unsigned char json_corpus_045[] = {
    0x5b, 0x78,
};
/* n_array_inner_array_no_comma */
static const unsigned char json_corpus_046[] = {
    0x5b, 0x33, 0x5b, 0x34, 0x5d, 0x5d,
};
/* n_array_invalid_utf8 */
static const unsigned char json_corpus_047[] = {
    0x5b, 0xff, 0x5d,
};
/* n_array_items_separated_by_semicolon */
static const unsigned char json_corpus_048[] = {
    0x5b, 0x31, 0x3a, 0x32, 0x5d,
};
/* n_array_just_comma */
static const unsigned char json_corpus_049[] = {
    0x5b, 0x2c, 0x5d,
};
/* n_array_just_minus */
static const unsigned char json_corpus_050[] = {
    0x5b, 0x2d, 0x5d,
};
/* n_array_missing_value */
static const unsigned char json_corpus_051[] = {
    0x5b, 0x20, 0x20, 0x20, 0x2c, 0x20, 0x22, 0x22, 0x5d,
};
/* n_array_newlines_unclosed */
static const unsigned char json_corpus_052[] = {
    0x5b, 0x22, 0x61, 0x22, 0x2c, 0x0a, 0x34, 0x0a, 0x2c, 0x31, 0x2c,
};
/* n_array_number_and_comma */
static const unsigned char json_corpus_053[] = {
    0x5b, 0x31, 0x2c, 0x5d,
};
/* n_array_number_and_several_commas */
static const unsigned char json_corpus_054[] = {
    0x5b, 0x31, 0x2c, 0x2c, 0x5d,
};
/* n_array_spaces_vertical_tab_formfeed */
static const unsigned char json_corpus_055[] = {
    0x5b, 0x22, 0x0b, 0x61, 0x22, 0x5c, 0x66, 0x5d,
};
/* n_array_star_inside */
static const unsigned char json_corpus_056[] = {
    0x5b, 0x2a, 0x5d,
};
/* n_array_unclosed */
static const unsigned char json_corpus_057[] = {
    0x5b, 0x22, 0x22,
};
/* n_array_unclosed_trailing_comma */
static const unsigned char json_corpus_058[] = {
    0x5b, 0x31, 0x2c,
};
/* n_array_unclosed_with_new_lines */
static const unsigned char json_corpus_059[] = {
    0x5b, 0x31, 0x2c, 0x0a, 0x31, 0x0a, 0x2c, 0x31,
};
/* n_array_unclosed_with_object_inside */
static const unsigned char json_corpus_060[] = {
    0x5b, 0x7b, 0x7d,
};
/* n_incomplete_false */
static const unsigned char json_corpus_061[] = {
    0x5b, 0x66, 0x61, 0x6c, 0x73, 0x5d,
};
/* n_incomplete_null */
static const unsigned char json_corpus_062[] = {
    0x5b, 0x6e, 0x75, 0x6c, 0x5d,
};
/* n_incomplete_true */
static const unsigned char json_corpus_063[] = {
    0x5b, 0x74, 0x72, 0x75, 0x5d,
};
/* n_multidigit_number_then_00 */
static const unsigned char json_corpus_064[] = {
    0x31, 0x32, 0x33, 0x00,
};
/* n_number_++ */
static const unsigned char json_corpus_065[] = {
    0x5b, 0x2b, 0x2b, 0x31, 0x32, 0x33, 0x34, 0x5d,
};
/* n_number_+1 */
static const unsigned char json_corpus_066[] = {
    0x5b, 0x2b, 0x31, 0x5d,
};
/* n_number_+Inf */
static const unsigned char json_corpus_067[] = {
    0x5b, 0x2b, 0x49, 0x6e, 0x66, 0x5d,
};
/* n_number_-01 */
static const unsigned char json_corpus_068[] = {
    0x5b, 0x2d, 0x30, 0x31, 0x5d,
};
/* n_number_-1.0. */
static const unsigned char json_corpus_069[] = {
    0x5b, 0x2d, 0x31, 0x2e, 0x30, 0x2e, 0x5d,
};
/* n_number_-2. */
static const unsigned char json_corpus_070[] = {
    0x5b, 0x2d, 0x32, 0x2e, 0x5d,
};
/* n_number_-NaN */
static const unsigned char json_corpus_071[] = {
    0x5b, 0x2d, 0x4e, 0x61, 0x4e, 0x5d,
};
/* n_number_.-1 */
static const unsigned char json_corpus_072[] = {
    0x5b, 0x2e, 0x2d, 0x31, 0x5d,
};
/* n_number_.2e-3 */
static const unsigned char json_corpus_073[] = {
    0x5b, 0x2e, 0x32, 0x65, 0x2d, 0x33, 0x5d,
};
/* n_number_0.1.2 */
static const unsigned char json_corpus_074[] = {
    0x5b, 0x30, 0x2e, 0x31, 0x2e, 0x32, 0x5d,
};
/* n_number_0.3e+ */
static const unsigned char json_corpus_075[] = {
    0x5b, 0x30, 0x2e, 0x33, 0x65, 0x2b, 0x5d,
};
/* n_number_0.3e */
static const unsigned char json_corpus_076[] = {
    0x5b, 0x30, 0x2e, 0x33, 0x65, 0x5d,
};
/* n_number_0.e1 */
static const unsigned char json_corpus_077[] = {
    0x5b, 0x30, 0x2e, 0x65, 0x31, 0x5d,
};
/* n_number_0_capital_E+ */
static const unsigned char json_corpus_078[] = {
    0x5b, 0x30, 0x45, 0x2b, 0x5d,
};
/* n_number_0_capital_E */
static const unsigned char json_corpus_079[] = {
    0x5b, 0x30, 0x45, 0x5d,
};
/* n_number_0e+ */
static const unsigned char json_corpus_080[] = {
    0x5b, 0x30, 0x65, 0x2b, 0x5d,
};
/* n_number_0e */
static const unsigned char json_corpus_081[] = {
    0x5b, 0x30, 0x65, 0x5d,
};
/* n_number_1.0e+ */
static const unsigned char json_corpus_082[] = {
    0x5b, 0x31, 0x2e, 0x30, 0x65, 0x2b, 0x5d,
};
/* n_number_1.0e- */
static const unsigned char json_corpus_083[] = {
    0x5b, 0x31, 0x2e, 0x30, 0x65, 0x2d, 0x5d,
};
/* n_number_1.0e */
static const unsigned char json_corpus_084[] = {
    0x5b, 0x31, 0x2e, 0x30, 0x65, 0x5d,
};
/* n_number_1_000 */
static const unsigned char json_corpus_085[] = {
    0x5b, 0x31, 0x20, 0x30, 0x30, 0x30, 0x2e, 0x30, 0x5d,
};
/* n_number_1eE2 */
static const unsigned char json_corpus_086[] = {
    0x5b, 0x31, 0x65, 0x45, 0x32, 0x5d,
};
/* n_number_2.e+3 */
static const unsigned char json_corpus_087[] = {
    0x5b, 0x32, 0x2e, 0x65, 0x2b, 0x33, 0x5d,
};
/* n_number_2.e-3 */
static const unsigned char json_corpus_088[] = {
    0x5b, 0x32, 0x2e, 0x65, 0x2d, 0x33, 0x5d,
};
/* n_number_2.e3 */
static const unsigned char json_corpus_089[] = {
    0x5b, 0x32, 0x2e, 0x65, 0x33, 0x5d,
};
/* n_number_9.e+ */
static const unsigned char json_corpus_090[] = {
    0x5b, 0x39, 0x2e, 0x65, 0x2b, 0x5d,
};
/* n_number_Inf */
static const unsigned char json_corpus_091[] = {
    0x5b, 0x49, 0x6e, 0x66, 0x5d,
};
/* n_number_NaN */
static const unsigned char json_corpus_092[] = {
    0x5b, 0x4e, 0x61, 0x4e, 0x5d,
};
/* n_number_U+FF11_fullwidth_digit_one */
static const unsigned char json_corpus_093[] = {
    0x5b, 0xef, 0xbc, 0x91, 0x5d,
};
/* n_number_expression */
static const unsigned char json_corpus_094[] = {
    0x5b, 0x31, 0x2b, 0x32, 0x5d,
};
/* n_number_hex_1_digit */
static const unsigned char json_corpus_095[] = {
    0x5b, 0x30, 0x78, 0x31, 0x5d,
};
/* n_number_hex_2_digits */
static const unsigned char json_corpus_096[] = {
    0x5b, 0x30, 0x78, 0x34, 0x32, 0x5d,
};
/* n_number_infinity */
static const unsigned char json_corpus_097[] = {
    0x5b, 0x49, 0x6e, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x5d,
};
/* n_number_invalid+- */
static const unsigned char json_corpus_098[] = {
    0x5b, 0x30, 0x65, 0x2b, 0x2d, 0x31, 0x5d,
};
/* n_number_invalid-negative-real */
static const unsigned char json_corpus_099[] = {
    0x5b, 0x2d, 0x31, 0x32, 0x33, 0x2e, 0x31, 0x32, 0x33, 0x66, 0x6f, 0x6f, 0x5d,
};
/* n_number_invalid-utf-8-in-bigger-int */
static const unsigned char json_corpus_100[] = {
    0x5b, 0x31, 0x32, 0x33, 0xe5, 0x5d,
};
/* n_number_invalid-utf-8-in-exponent */
static const unsigned char json_corpus_101[] = {
    0x5b, 0x31, 0x65, 0x31, 0xe5, 0x5d,
};
/* n_number_invalid-utf-8-in-int */
static const unsigned char json_corpus_102[] = {
    0x5b, 0x30, 0xe5, 0x5d, 0x0a,
};
/* n_number_minus_infinity */
static const unsigned char json_corpus_103[] = {
    0x5b, 0x2d, 0x49, 0x6e, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x5d,
};
/* n_number_minus_sign_with_trailing_garbage */
static const unsigned char json_corpus_104[] = {
    0x5b, 0x2d, 0x66, 0x6f, 0x6f, 0x5d,
};
/* n_number_minus_space_1 */
static const unsigned char json_corpus_105[] = {
    0x5b, 0x2d, 0x20, 0x31, 0x5d,
};
/* n_number_neg_int_starting_with_zero */
static const unsigned char json_corpus_106[] = {
    0x5b, 0x2d, 0x30, 0x31, 0x32, 0x5d,
};
/* n_number_neg_real_without_int_part */
static const unsigned char json_corpus_107[] = {
    0x5b, 0x2d, 0x2e, 0x31, 0x32, 0x33, 0x5d,
};
/* n_number_neg_with_garbage_at_end */
static const unsigned char json_corpus_108[] = {
    0x5b, 0x2d, 0x31, 0x78, 0x5d,
};
/* n_number_real_garbage_after_e */
static const unsigned char json_corpus_109[] = {
    0x5b, 0x31, 0x65, 0x61, 0x5d,
};
/* n_number_real_with_invalid_utf8_after_e */
static const unsigned char json_corpus_110[] = {
    0x5b, 0x31, 0x65, 0xe5, 0x5d,
};
/* n_number_real_without_fractional_part */
static const unsigned char json_corpus_111[] = {
    0x5b, 0x31, 0x2e, 0x5d,
};
/* n_number_starting_with_dot */
static const unsigned char json_corpus_112[] = {
    0x5b, 0x2e, 0x31, 0x32, 0x33, 0x5d,
};
/* n_number_with_alpha */
static const unsigned char json_corpus_113[] = {
    0x5b, 0x31, 0x2e, 0x32, 0x61, 0x2d, 0x33, 0x5d,
};
/* n_number_with_alpha_char */
static const unsigned char json_corpus_114[] = {
    0x5b, 0x31, 0x2e, 0x38, 0x30, 0x31, 0x31, 0x36, 0x37, 0x30, 0x30, 0x33, 0x33, 0x33, 0x37, 0x36,
    0x35, 0x31, 0x34, 0x48, 0x2d, 0x33, 0x30, 0x38, 0x5d,
};
/* n_number_with_leading_zero */
static const unsigned char json_corpus_115[] = {
    0x5b, 0x30, 0x31, 0x32, 0x5d,
};
/* n_object_bad_value */
static const unsigned char json_corpus_116[] = {
    0x5b, 0x22, 0x78, 0x22, 0x2c, 0x20, 0x74, 0x72, 0x75, 0x74, 0x68, 0x5d,
};
/* n_object_bracket_key */
static const unsigned char json_corpus_117[] = {
    0x7b, 0x5b, 0x3a, 0x20, 0x22, 0x78, 0x22, 0x7d, 0x0a,
};
/* n_object_comma_instead_of_colon */
static const unsigned char json_corpus_118[] = {
    0x7b, 0x22, 0x78, 0x22, 0x2c, 0x20, 0x6e, 0x75, 0x6c, 0x6c, 0x7d,
};
/* n_object_double_colon */
static const unsigned char json_corpus_119[] = {
    0x7b, 0x22, 0x78, 0x22, 0x3a, 0x3a, 0x22, 0x62, 0x22, 0x7d,
};
/* n_object_emoji */
static const unsigned char json_corpus_120[] = {
    0x7b, 0xf0, 0x9f, 0x87, 0xa8, 0xf0, 0x9f, 0x87, 0xad, 0x7d,
};
/* n_object_garbage_at_end */
static const unsigned char json_corpus_121[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x61, 0x22, 0x20, 0x31, 0x32, 0x33, 0x7d,
};
/* n_object_key_with_single_quotes */
static const unsigned char json_corpus_122[] = {
    0x7b, 0x6b, 0x65, 0x79, 0x3a, 0x20, 0x27, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x27, 0x7d,
};
/* n_object_lone_continuation_byte_in_key_and_trailing_comma */
static const unsigned char json_corpus_123[] = {
    0x7b, 0x22, 0xb9, 0x22, 0x3a, 0x22, 0x30, 0x22, 0x2c, 0x7d,
};
/* n_object_missing_colon */
static const unsigned char json_corpus_124[] = {
    0x7b, 0x22, 0x61, 0x22, 0x20, 0x62, 0x7d,
};
/* n_object_missing_key */
static const unsigned char json_corpus_125[] = {
    0x7b, 0x3a, 0x22, 0x62, 0x22, 0x7d,
};
/* n_object_missing_semicolon */
static const unsigned char json_corpus_126[] = {
    0x7b, 0x22, 0x61, 0x22, 0x20, 0x22, 0x62, 0x22, 0x7d,
};
/* n_object_missing_value */
static const unsigned char json_corpus_127[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a,
};
/* n_object_no-colon */
static const unsigned char json_corpus_128[] = {
    0x7b, 0x22, 0x61, 0x22,
};
/* n_object_non_string_key */
static const unsigned char json_corpus_129[] = {
    0x7b, 0x31, 0x3a, 0x31, 0x7d,
};
/* n_object_non_string_key_but_huge_number_instead */
static const unsigned char json_corpus_130[] = {
    0x7b, 0x39, 0x39, 0x39, 0x39, 0x45, 0x39, 0x39, 0x39, 0x39, 0x3a, 0x31, 0x7d,
};
/* n_object_repeated_null_null */
static const unsigned char json_corpus_131[] = {
    0x7b, 0x6e, 0x75, 0x6c, 0x6c, 0x3a, 0x6e, 0x75, 0x6c, 0x6c, 0x2c, 0x6e, 0x75, 0x6c, 0x6c, 0x3a,
    0x6e, 0x75, 0x6c, 0x6c, 0x7d,
};
/* n_object_several_trailing_commas */
static const unsigned char json_corpus_132[] = {
    0x7b, 0x22, 0x69, 0x64, 0x22, 0x3a, 0x30, 0x2c, 0x2c, 0x2c, 0x2c, 0x2c, 0x7d,
};
/* n_object_single_quote */
static const unsigned char json_corpus_133[] = {
    0x7b, 0x27, 0x61, 0x27, 0x3a, 0x30, 0x7d,
};
/* n_object_trailing_comma */
static const unsigned char json_corpus_134[] = {
    0x7b, 0x22, 0x69, 0x64, 0x22, 0x3a, 0x30, 0x2c, 0x7d,
};
/* n_object_trailing_comment */
static const unsigned char json_corpus_135[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x7d, 0x2f, 0x2a, 0x2a, 0x2f,
};
/* n_object_trailing_comment_open */
static const unsigned char json_corpus_136[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x7d, 0x2f, 0x2a, 0x2a, 0x2f, 0x2f,
};
/* n_object_trailing_comment_slash_open */
static const unsigned char json_corpus_137[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x7d, 0x2f, 0x2f,
};
/* n_object_trailing_comment_slash_open_incomplete */
static const unsigned char json_corpus_138[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x7d, 0x2f,
};
/* n_object_two_commas_in_a_row */
static const unsigned char json_corpus_139[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x2c, 0x2c, 0x22, 0x63, 0x22, 0x3a, 0x22, 0x64,
    0x22, 0x7d,
};
/* n_object_unquoted_key */
static const unsigned char json_corpus_140[] = {
    0x7b, 0x61, 0x3a, 0x20, 0x22, 0x62, 0x22, 0x7d,
};
/* n_object_unterminated-value */
static const unsigned char json_corpus_141[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x61,
};
/* n_object_with_single_string */
static const unsigned char json_corpus_142[] = {
    0x7b, 0x20, 0x22, 0x66, 0x6f, 0x6f, 0x22, 0x20, 0x3a, 0x20, 0x22, 0x62, 0x61, 0x72, 0x22, 0x2c,
    0x20, 0x22, 0x61, 0x22, 0x20, 0x7d,
};
/* n_object_with_trailing_garbage */
static const unsigned char json_corpus_143[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x7d, 0x23,
};
/* n_single_space */
static const unsigned char json_corpus_144[] = {
    0x20,
};
/* n_string_1_surrogate_then_escape */
static const unsigned char json_corpus_145[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x22, 0x5d,
};
/* n_string_1_surrogate_then_escape_u */
static const unsigned char json_corpus_146[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x75, 0x22, 0x5d,
};
/* n_string_1_surrogate_then_escape_u1 */
static const unsigned char json_corpus_147[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x75, 0x31, 0x22, 0x5d,
};
/* n_string_1_surrogate_then_escape_u1x */
static const unsigned char json_corpus_148[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x75, 0x31, 0x78, 0x22, 0x5d,
};
/* n_string_accentuated_char_no_quotes */
static const unsigned char json_corpus_149[] = {
    0x5b, 0xc3, 0xa9, 0x5d,
};
/* n_string_backslash_00 */
static const unsigned char json_corpus_150[] = {
    0x5b, 0x22, 0x5c, 0x00, 0x22, 0x5d,
};
/* n_string_escape_x */
static const unsigned char json_corpus_151[] = {
    0x5b, 0x22, 0x5c, 0x78, 0x30, 0x30, 0x22, 0x5d,
};
/* n_string_escaped_backslash_bad */
static const unsigned char json_corpus_152[] = {
    0x5b, 0x22, 0x5c, 0x5c, 0x5c, 0x22, 0x5d,
};
/* n_string_escaped_ctrl_char_tab */
static const unsigned char json_corpus_153[] = {
    0x5b, 0x22, 0x5c, 0x09, 0x22, 0x5d,
};
/* n_string_escaped_emoji */
static const unsigned char json_corpus_154[] = {
    0x5b, 0x22, 0x5c, 0xf0, 0x9f, 0x8c, 0x80, 0x22, 0x5d,
};
/* n_string_incomplete_escape */
static const unsigned char json_corpus_155[] = {
    0x5b, 0x22, 0x5c, 0x22, 0x5d,
};
/* n_string_incomplete_escaped_character */
static const unsigned char json_corpus_156[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x41, 0x22, 0x5d,
};
/* n_string_incomplete_surrogate */
static const unsigned char json_corpus_157[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x33, 0x34, 0x5c, 0x75, 0x44, 0x64, 0x22, 0x5d,
};
/* n_string_incomplete_surrogate_escape_invalid */
static const unsigned char json_corpus_158[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x30, 0x5c, 0x78,
    0x22, 0x5d,
};
/* n_string_invalid-utf-8-in-escape */
static const unsigned char json_corpus_159[] = {
    0x5b, 0x22, 0x5c, 0x75, 0xe5, 0x22, 0x5d,
};
/* n_string_invalid_backslash_esc */
static const unsigned char json_corpus_160[] = {
    0x5b, 0x22, 0x5c, 0x61, 0x22, 0x5d,
};
/* n_string_invalid_unicode_escape */
static const unsigned char json_corpus_161[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x71, 0x71, 0x71, 0x71, 0x22, 0x5d,
};
/* n_string_invalid_utf8_after_escape */
static const unsigned char json_corpus_162[] = {
    0x5b, 0x22, 0x5c, 0xe5, 0x22, 0x5d,
};
/* n_string_leading_uescaped_thinspace */
static const unsigned char json_corpus_163[] = {
    0x5b, 0x5c, 0x75, 0x30, 0x30, 0x32, 0x30, 0x22, 0x61, 0x73, 0x64, 0x22, 0x5d,
};
/* n_string_no_quotes_with_bad_escape */
static const unsigned char json_corpus_164[] = {
    0x5b, 0x5c, 0x6e, 0x5d,
};
/* n_string_single_doublequote */
static const unsigned char json_corpus_165[] = {
    0x22,
};
/* n_string_single_quote */
static const unsigned char json_corpus_166[] = {
    0x5b, 0x27, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x20, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x27, 0x5d,
};
/* n_string_single_string_no_double_quotes */
static const unsigned char json_corpus_167[] = {
    0x61, 0x62, 0x63,
};
/* n_string_start_escape_unclosed */
static const unsigned char json_corpus_168[] = {
    0x5b, 0x22, 0x5c,
};
/* n_string_unescaped_ctrl_char */
static const unsigned char json_corpus_169[] = {
    0x5b, 0x22, 0x61, 0x00, 0x61, 0x22, 0x5d,
};
/* n_string_unescaped_newline */
static const unsigned char json_corpus_170[] = {
    0x5b, 0x22, 0x6e, 0x65, 0x77, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x5d,
};
/* n_string_unescaped_tab */
static const unsigned char json_corpus_171[] = {
    0x5b, 0x22, 0x09, 0x22, 0x5d,
};
/* n_string_unicode_CapitalU */
static const unsigned char json_corpus_172[] = {
    0x22, 0x5c, 0x55, 0x41, 0x36, 0x36, 0x44, 0x22,
};
/* n_string_with_trailing_garbage */
static const unsigned char json_corpus_173[] = {
    0x22, 0x22, 0x78,
};
/* n_structure_U+2060_word_joined */
static const unsigned char json_corpus_174[] = {
    0x5b, 0xe2, 0x81, 0xa0, 0x5d,
};
/* n_structure_UTF8_BOM_no_data */
static const unsigned char json_corpus_175[] = {
    0xef, 0xbb, 0xbf,
};
/* n_structure_angle_bracket_. */
static const unsigned char json_corpus_176[] = {
    0x3c, 0x2e, 0x3e,
};
/* n_structure_angle_bracket_null */
static const unsigned char json_corpus_177[] = {
    0x5b, 0x3c, 0x6e, 0x75, 0x6c, 0x6c, 0x3e, 0x5d,
};
/* n_structure_array_trailing_garbage */
static const unsigned char json_corpus_178[] = {
    0x5b, 0x31, 0x5d, 0x78,
};
/* n_structure_array_with_extra_array_close */
static const unsigned char json_corpus_179[] = {
    0x5b, 0x31, 0x5d, 0x5d,
};
/* n_structure_array_with_unclosed_string */
static const unsigned char json_corpus_180[] = {
    0x5b, 0x22, 0x61, 0x73, 0x64, 0x5d,
};
/* n_structure_ascii-unicode-identifier */
static const unsigned char json_corpus_181[] = {
    0x61, 0xc3, 0xa5,
};
/* n_structure_capitalized_True */
static const unsigned char json_corpus_182[] = {
    0x5b, 0x54, 0x72, 0x75, 0x65, 0x5d,
};
/* n_structure_close_unopened_array */
static const unsigned char json_corpus_183[] = {
    0x31, 0x5d,
};
/* n_structure_comma_instead_of_closing_brace */
static const unsigned char json_corpus_184[] = {
    0x7b, 0x22, 0x78, 0x22, 0x3a, 0x20, 0x74, 0x72, 0x75, 0x65, 0x2c,
};
/* n_structure_double_array */
static const unsigned char json_corpus_185[] = {
    0x5b, 0x5d, 0x5b, 0x5d,
};
/* n_structure_end_array */
static const unsigned char json_corpus_186[] = {
    0x5d,
};
/* n_structure_incomplete_UTF8_BOM */
static const unsigned char json_corpus_187[] = {
    0xef, 0xbb, 0x7b, 0x7d,
};
/* n_structure_lone-invalid-utf-8 */
static const unsigned char json_corpus_188[] = {
    0xe5,
};
/* n_structure_lone-open-bracket */
static const unsigned char json_corpus_189[] = {
    0x5b,
};
/* n_structure_no_data */
static const unsigned char json_corpus_190[] = {
};
/* n_structure_null-byte-outside-string */
static const unsigned char json_corpus_191[] = {
    0x5b, 0x00, 0x5d,
};
/* n_structure_number_with_trailing_garbage */
static const unsigned char json_corpus_192[] = {
    0x32, 0x40,
};
/* n_structure_object_followed_by_closing_object */
static const unsigned char json_corpus_193[] = {
    0x7b, 0x7d, 0x7d,
};
/* n_structure_object_unclosed_no_value */
static const unsigned char json_corpus_194[] = {
    0x7b, 0x22, 0x22, 0x3a,
};
/* n_structure_object_with_comment */
static const unsigned char json_corpus_195[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x2f, 0x2a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2a, 0x2f,
    0x22, 0x62, 0x22, 0x7d,
};
/* n_structure_object_with_trailing_garbage */
static const unsigned char json_corpus_196[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x20, 0x74, 0x72, 0x75, 0x65, 0x7d, 0x20, 0x22, 0x78, 0x22,
};
/* n_structure_open_array_apostrophe */
static const unsigned char json_corpus_197[] = {
    0x5b, 0x27,
};
/* n_structure_open_array_comma */
static const unsigned char json_corpus_198[] = {
    0x5b, 0x2c,
};
/* n_structure_open_array_open_object */
static const unsigned char json_corpus_199[] = {
    0x5b, 0x7b,
};
/* n_structure_open_array_open_string */
static const unsigned char json_corpus_200[] = {
    0x5b, 0x22, 0x61,
};
/* n_structure_open_array_string */
static const unsigned char json_corpus_201[] = {
    0x5b, 0x22, 0x61, 0x22,
};
/* n_structure_open_object */
static const unsigned char json_corpus_202[] = {
    0x7b,
};
/* n_structure_open_object_close_array */
static const unsigned char json_corpus_203[] = {
    0x7b, 0x5d,
};
/* n_structure_open_object_comma */
static const unsigned char json_corpus_204[] = {
    0x7b, 0x2c,
};
/* n_structure_open_object_open_array */
static const unsigned char json_corpus_205[] = {
    0x7b, 0x5b,
};
/* n_structure_open_object_open_string */
static const unsigned char json_corpus_206[] = {
    0x7b, 0x22, 0x61,
};
/* n_structure_open_object_string_with_apostrophes */
static const unsigned char json_corpus_207[] = {
    0x7b, 0x27, 0x61, 0x27,
};
/* n_structure_open_open */
static const unsigned char json_corpus_208[] = {
    0x5b, 0x22, 0x5c, 0x7b, 0x5b, 0x22, 0x5c, 0x7b, 0x5b, 0x22, 0x5c, 0x7b, 0x5b, 0x22, 0x5c, 0x7b,
};
/* n_structure_single_eacute */
static const unsigned char json_corpus_209[] = {
    0xe9,
};
/* n_structure_single_star */
static const unsigned char json_corpus_210[] = {
    0x2a,
};
/* n_structure_trailing_# */
static const unsigned char json_corpus_211[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x7d, 0x23, 0x7b, 0x7d,
};
/* n_structure_uescaped_LF_before_string */
static const unsigned char json_corpus_212[] = {
    0x5b, 0x5c, 0x75, 0x30, 0x30, 0x30, 0x41, 0x22, 0x22, 0x5d,
};
/* n_structure_unclosed_array */
static const unsigned char json_corpus_213[] = {
    0x5b, 0x31,
};
/* n_structure_unclosed_array_partial_null */
static const unsigned char json_corpus_214[] = {
    0x5b, 0x20, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0x20, 0x6e, 0x75, 0x6c,
};
/* n_structure_unclosed_array_unfinished_false */
static const unsigned char json_corpus_215[] = {
    0x5b, 0x20, 0x74, 0x72, 0x75, 0x65, 0x2c, 0x20, 0x66, 0x61, 0x6c, 0x73,
};
/* n_structure_unclosed_array_unfinished_true */
static const unsigned char json_corpus_216[] = {
    0x5b, 0x20, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0x20, 0x74, 0x72, 0x75,
};
/* n_structure_unclosed_object */
static const unsigned char json_corpus_217[] = {
    0x7b, 0x22, 0x61, 0x73, 0x64, 0x22, 0x3a, 0x22, 0x61, 0x73, 0x64, 0x22,
};
/* n_structure_unicode-identifier */
static const unsigned char json_corpus_218[] = {
    0xc3, 0xa5,
};
/* n_structure_whitespace_U+2060_word_joiner */
static const unsigned char json_corpus_219[] = {
    0x5b, 0xe2, 0x81, 0xa0, 0x5d,
};
/* n_structure_whitespace_formfeed */
static const unsigned char json_corpus_220[] = {
    0x5b, 0x0c, 0x5d,
};
/* y_array_arraysWithSpaces */
static const unsigned char json_corpus_221[] = {
    0x5b, 0x5b, 0x5d, 0x20, 0x20, 0x20, 0x5d,
};
/* y_array_empty-string */
static const unsigned char json_corpus_222[] = {
    0x5b, 0x22, 0x22, 0x5d,
};
/* y_array_empty */
static const unsigned char json_corpus_223[] = {
    0x5b, 0x5d,
};
/* y_array_ending_with_newline */
static const unsigned char json_corpus_224[] = {
    0x5b, 0x22, 0x61, 0x22, 0x5d,
};
/* y_array_false */
static const unsigned char json_corpus_225[] = {
    0x5b, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x5d,
};
/* y_array_heterogeneous */
static const unsigned char json_corpus_226[] = {
    0x5b, 0x6e, 0x75, 0x6c, 0x6c, 0x2c, 0x20, 0x31, 0x2c, 0x20, 0x22, 0x31, 0x22, 0x2c, 0x20, 0x7b,
    0x7d, 0x5d,
};
/* y_array_null */
static const unsigned char json_corpus_227[] = {
    0x5b, 0x6e, 0x75, 0x6c, 0x6c, 0x5d,
};
/* y_array_with_1_and_newline */
static const unsigned char json_corpus_228[] = {
    0x5b, 0x31, 0x0a, 0x5d,
};
/* y_array_with_leading_space */
static const unsigned char json_corpus_229[] = {
    0x20, 0x5b, 0x31, 0x5d,
};
/* y_array_with_several_null */
static const unsigned char json_corpus_230[] = {
    0x5b, 0x31, 0x2c, 0x6e, 0x75, 0x6c, 0x6c, 0x2c, 0x6e, 0x75, 0x6c, 0x6c, 0x2c, 0x6e, 0x75, 0x6c,
    0x6c, 0x2c, 0x32, 0x5d,
};
/* y_array_with_trailing_space */
static const unsigned char json_corpus_231[] = {
    0x5b, 0x32, 0x5d, 0x20,
};
/* y_number */
static const unsigned char json_corpus_232[] = {
    0x5b, 0x31, 0x32, 0x33, 0x65, 0x36, 0x35, 0x5d,
};
/* y_number_0e+1 */
static const unsigned char json_corpus_233[] = {
    0x5b, 0x30, 0x65, 0x2b, 0x31, 0x5d,
};
/* y_number_0e1 */
static const unsigned char json_corpus_234[] = {
    0x5b, 0x30, 0x65, 0x31, 0x5d,
};
/* y_number_after_space */
static const unsigned char json_corpus_235[] = {
    0x5b, 0x20, 0x34, 0x5d,
};
/* y_number_double_close_to_zero */
static const unsigned char json_corpus_236[] = {
    0x5b, 0x2d, 0x30, 0x2e, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
    0x30, 0x31, 0x5d, 0x0a,
};
/* y_number_int_with_exp */
static const unsigned char json_corpus_237[] = {
    0x5b, 0x32, 0x30, 0x65, 0x31, 0x5d,
};
/* y_number_minus_zero */
static const unsigned char json_corpus_238[] = {
    0x5b, 0x2d, 0x30, 0x5d,
};
/* y_number_negative_int */
static const unsigned char json_corpus_239[] = {
    0x5b, 0x2d, 0x31, 0x32, 0x33, 0x5d,
};
/* y_number_negative_one */
static const unsigned char json_corpus_240[] = {
    0x5b, 0x2d, 0x31, 0x5d,
};
/* y_number_negative_zero */
static const unsigned char json_corpus_241[] = {
    0x5b, 0x2d, 0x30, 0x5d,
};
/* y_number_real_capital_e */
static const unsigned char json_corpus_242[] = {
    0x5b, 0x31, 0x45, 0x32, 0x32, 0x5d,
};
/* y_number_real_capital_e_neg_exp */
static const unsigned char json_corpus_243[] = {
    0x5b, 0x31, 0x45, 0x2d, 0x32, 0x5d,
};
/* y_number_real_capital_e_pos_exp */
static const unsigned char json_corpus_244[] = {
    0x5b, 0x31, 0x45, 0x2b, 0x32, 0x5d,
};
/* y_number_real_exponent */
static const unsigned char json_corpus_245[] = {
    0x5b, 0x31, 0x32, 0x33, 0x65, 0x34, 0x35, 0x5d,
};
/* y_number_real_fraction_exponent */
static const unsigned char json_corpus_246[] = {
    0x5b, 0x31, 0x32, 0x33, 0x2e, 0x34, 0x35, 0x36, 0x65, 0x37, 0x38, 0x5d,
};
/* y_number_real_neg_exp */
static const unsigned char json_corpus_247[] = {
    0x5b, 0x31, 0x65, 0x2d, 0x32, 0x5d,
};
/* y_number_real_pos_exponent */
static const unsigned char json_corpus_248[] = {
    0x5b, 0x31, 0x65, 0x2b, 0x32, 0x5d,
};
/* y_number_simple_int */
static const unsigned char json_corpus_249[] = {
    0x5b, 0x31, 0x32, 0x33, 0x5d,
};
/* y_number_simple_real */
static const unsigned char json_corpus_250[] = {
    0x5b, 0x31, 0x32, 0x33, 0x2e, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x5d,
};
/* y_object */
static const unsigned char json_corpus_251[] = {
    0x7b, 0x22, 0x61, 0x73, 0x64, 0x22, 0x3a, 0x22, 0x73, 0x64, 0x66, 0x22, 0x2c, 0x20, 0x22, 0x64,
    0x66, 0x67, 0x22, 0x3a, 0x22, 0x66, 0x67, 0x68, 0x22, 0x7d,
};
/* y_object_basic */
static const unsigned char json_corpus_252[] = {
    0x7b, 0x22, 0x61, 0x73, 0x64, 0x22, 0x3a, 0x22, 0x73, 0x64, 0x66, 0x22, 0x7d,
};
/* y_object_duplicated_key */
static const unsigned char json_corpus_253[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x2c, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x63, 0x22,
    0x7d,
};
/* y_object_duplicated_key_and_value */
static const unsigned char json_corpus_254[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22, 0x2c, 0x22, 0x61, 0x22, 0x3a, 0x22, 0x62, 0x22,
    0x7d,
};
/* y_object_empty */
static const unsigned char json_corpus_255[] = {
    0x7b, 0x7d,
};
/* y_object_empty_key */
static const unsigned char json_corpus_256[] = {
    0x7b, 0x22, 0x22, 0x3a, 0x30, 0x7d,
};
/* y_object_escaped_null_in_key */
static const unsigned char json_corpus_257[] = {
    0x7b, 0x22, 0x66, 0x6f, 0x6f, 0x5c, 0x75, 0x30, 0x30, 0x30, 0x30, 0x62, 0x61, 0x72, 0x22, 0x3a,
    0x20, 0x34, 0x32, 0x7d,
};
/* y_object_extreme_numbers */
static const unsigned char json_corpus_258[] = {
    0x7b, 0x20, 0x22, 0x6d, 0x69, 0x6e, 0x22, 0x3a, 0x20, 0x2d, 0x31, 0x2e, 0x30, 0x65, 0x2b, 0x32,
    0x38, 0x2c, 0x20, 0x22, 0x6d, 0x61, 0x78, 0x22, 0x3a, 0x20, 0x31, 0x2e, 0x30, 0x65, 0x2b, 0x32,
    0x38, 0x20, 0x7d,
};
/* y_object_long_strings */
static const unsigned char json_corpus_259[] = {
    0x7b, 0x22, 0x78, 0x22, 0x3a, 0x5b, 0x7b, 0x22, 0x69, 0x64, 0x22, 0x3a, 0x20, 0x22, 0x78, 0x78,
    0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78,
    0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78,
    0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x22, 0x7d, 0x5d, 0x2c, 0x20, 0x22, 0x69, 0x64, 0x22, 0x3a,
    0x20, 0x22, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78,
    0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78,
    0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x22, 0x7d,
};
/* y_object_simple */
static const unsigned char json_corpus_260[] = {
    0x7b, 0x22, 0x61, 0x22, 0x3a, 0x5b, 0x5d, 0x7d,
};
/* y_object_string_unicode */
static const unsigned char json_corpus_261[] = {
    0x7b, 0x22, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x3a, 0x22, 0x5c, 0x75, 0x30, 0x34, 0x31, 0x66,
    0x5c, 0x75, 0x30, 0x34, 0x33, 0x65, 0x5c, 0x75, 0x30, 0x34, 0x33, 0x62, 0x5c, 0x75, 0x30, 0x34,
    0x34, 0x32, 0x5c, 0x75, 0x30, 0x34, 0x33, 0x65, 0x5c, 0x75, 0x30, 0x34, 0x34, 0x30, 0x5c, 0x75,
    0x30, 0x34, 0x33, 0x30, 0x20, 0x5c, 0x75, 0x30, 0x34, 0x31, 0x37, 0x5c, 0x75, 0x30, 0x34, 0x33,
    0x35, 0x5c, 0x75, 0x30, 0x34, 0x33, 0x63, 0x5c, 0x75, 0x30, 0x34, 0x33, 0x62, 0x5c, 0x75, 0x30,
    0x34, 0x33, 0x35, 0x5c, 0x75, 0x30, 0x34, 0x33, 0x61, 0x5c, 0x75, 0x30, 0x34, 0x33, 0x65, 0x5c,
    0x75, 0x30, 0x34, 0x33, 0x66, 0x5c, 0x75, 0x30, 0x34, 0x33, 0x30, 0x22, 0x20, 0x7d,
};
/* y_object_with_newlines */
static const unsigned char json_corpus_262[] = {
    0x7b, 0x0a, 0x22, 0x61, 0x22, 0x3a, 0x20, 0x22, 0x62, 0x22, 0x0a, 0x7d,
};
/* y_string_1_2_3_bytes_UTF-8_sequences */
static const unsigned char json_corpus_263[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x36, 0x30, 0x5c, 0x75, 0x30, 0x31, 0x32, 0x61, 0x5c, 0x75,
    0x31, 0x32, 0x41, 0x42, 0x22, 0x5d,
};
/* y_string_accepted_surrogate_pair */
static const unsigned char json_corpus_264[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x30, 0x31, 0x5c, 0x75, 0x64, 0x63, 0x33, 0x37, 0x22, 0x5d,
};
/* y_string_accepted_surrogate_pairs */
static const unsigned char json_corpus_265[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x64, 0x38, 0x33, 0x64, 0x5c, 0x75, 0x64, 0x65, 0x33, 0x39, 0x5c, 0x75,
    0x64, 0x38, 0x33, 0x64, 0x5c, 0x75, 0x64, 0x63, 0x38, 0x64, 0x22, 0x5d,
};
/* y_string_allowed_escapes */
static const unsigned char json_corpus_266[] = {
    0x5b, 0x22, 0x5c, 0x22, 0x5c, 0x5c, 0x5c, 0x2f, 0x5c, 0x62, 0x5c, 0x66, 0x5c, 0x6e, 0x5c, 0x72,
    0x5c, 0x74, 0x22, 0x5d,
};
/* y_string_backslash_and_u_escaped_zero */
static const unsigned char json_corpus_267[] = {
    0x5b, 0x22, 0x5c, 0x5c, 0x75, 0x30, 0x30, 0x30, 0x30, 0x22, 0x5d,
};
/* y_string_backslash_doublequotes */
static const unsigned char json_corpus_268[] = {
    0x5b, 0x22, 0x5c, 0x22, 0x22, 0x5d,
};
/* y_string_comments */
static const unsigned char json_corpus_269[] = {
    0x5b, 0x22, 0x61, 0x2f, 0x2a, 0x62, 0x2a, 0x2f, 0x63, 0x2f, 0x2a, 0x64, 0x2f, 0x2f, 0x65, 0x22,
    0x5d,
};
/* y_string_double_escape_a */
static const unsigned char json_corpus_270[] = {
    0x5b, 0x22, 0x5c, 0x5c, 0x61, 0x22, 0x5d,
};
/* y_string_double_escape_n */
static const unsigned char json_corpus_271[] = {
    0x5b, 0x22, 0x5c, 0x5c, 0x6e, 0x22, 0x5d,
};
/* y_string_escaped_control_character */
static const unsigned char json_corpus_272[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x31, 0x32, 0x22, 0x5d,
};
/* y_string_escaped_noncharacter */
static const unsigned char json_corpus_273[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x46, 0x46, 0x46, 0x46, 0x22, 0x5d,
};
/* y_string_in_array */
static const unsigned char json_corpus_274[] = {
    0x5b, 0x22, 0x61, 0x73, 0x64, 0x22, 0x5d,
};
/* y_string_in_array_with_leading_space */
static const unsigned char json_corpus_275[] = {
    0x5b, 0x20, 0x22, 0x61, 0x73, 0x64, 0x22, 0x5d,
};
/* y_string_last_surrogates_1_and_2 */
static const unsigned char json_corpus_276[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x42, 0x46, 0x46, 0x5c, 0x75, 0x44, 0x46, 0x46, 0x46, 0x22, 0x5d,
};
/* y_string_nbsp_uescaped */
static const unsigned char json_corpus_277[] = {
    0x5b, 0x22, 0x6e, 0x65, 0x77, 0x5c, 0x75, 0x30, 0x30, 0x41, 0x30, 0x6c, 0x69, 0x6e, 0x65, 0x22,
    0x5d,
};
/* y_string_nonCharacterInUTF-8_U+10FFFF */
static const unsigned char json_corpus_278[] = {
    0x5b, 0x22, 0xf4, 0x8f, 0xbf, 0xbf, 0x22, 0x5d,
};
/* y_string_nonCharacterInUTF-8_U+FFFF */
static const unsigned char json_corpus_279[] = {
    0x5b, 0x22, 0xef, 0xbf, 0xbf, 0x22, 0x5d,
};
/* y_string_null_escape */
static const unsigned char json_corpus_280[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x30, 0x30, 0x22, 0x5d,
};
/* y_string_one-byte-utf-8 */
static const unsigned char json_corpus_281[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x32, 0x63, 0x22, 0x5d,
};
/* y_string_pi */
static const unsigned char json_corpus_282[] = {
    0x5b, 0x22, 0xcf, 0x80, 0x22, 0x5d,
};
/* y_string_reservedCharacterInUTF-8_U+1BFFF */
static const unsigned char json_corpus_283[] = {
    0x5b, 0x22, 0xf0, 0x9b, 0xbf, 0xbf, 0x22, 0x5d,
};
/* y_string_simple_ascii */
static const unsigned char json_corpus_284[] = {
    0x5b, 0x22, 0x61, 0x73, 0x64, 0x20, 0x22, 0x5d,
};
/* y_string_space */
static const unsigned char json_corpus_285[] = {
    0x22, 0x20, 0x22,
};
/* y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF */
static const unsigned char json_corpus_286[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x33, 0x34, 0x5c, 0x75, 0x44, 0x64, 0x31, 0x65, 0x22, 0x5d,
};
/* y_string_three-byte-utf-8 */
static const unsigned char json_corpus_287[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x38, 0x32, 0x31, 0x22, 0x5d,
};
/* y_string_two-byte-utf-8 */
static const unsigned char json_corpus_288[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x31, 0x32, 0x33, 0x22, 0x5d,
};
/* y_string_u+2028_line_sep */
static const unsigned char json_corpus_289[] = {
    0x5b, 0x22, 0xe2, 0x80, 0xa8, 0x22, 0x5d,
};
/* y_string_u+2029_par_sep */
static const unsigned char json_corpus_290[] = {
    0x5b, 0x22, 0xe2, 0x80, 0xa9, 0x22, 0x5d,
};
/* y_string_uEscape */
static const unsigned char json_corpus_291[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x36, 0x31, 0x5c, 0x75, 0x33, 0x30, 0x61, 0x66, 0x5c, 0x75,
    0x33, 0x30, 0x45, 0x41, 0x5c, 0x75, 0x33, 0x30, 0x62, 0x39, 0x22, 0x5d,
};
/* y_string_uescaped_newline */
static const unsigned char json_corpus_292[] = {
    0x5b, 0x22, 0x6e, 0x65, 0x77, 0x5c, 0x75, 0x30, 0x30, 0x30, 0x41, 0x6c, 0x69, 0x6e, 0x65, 0x22,
    0x5d,
};
/* y_string_unescaped_char_delete */
static const unsigned char json_corpus_293[] = {
    0x5b, 0x22, 0x7f, 0x22, 0x5d,
};
/* y_string_unicode */
static const unsigned char json_corpus_294[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x41, 0x36, 0x36, 0x44, 0x22, 0x5d,
};
/* y_string_unicodeEscapedBackslash */
static const unsigned char json_corpus_295[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x35, 0x43, 0x22, 0x5d,
};
/* y_string_unicode_2 */
static const unsigned char json_corpus_296[] = {
    0x5b, 0x22, 0xe2, 0x8d, 0x82, 0xe3, 0x88, 0xb4, 0xe2, 0x8d, 0x82, 0x22, 0x5d,
};
/* y_string_unicode_U+10FFFE_nonchar */
static const unsigned char json_corpus_297[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x42, 0x46, 0x46, 0x5c, 0x75, 0x44, 0x46, 0x46, 0x45, 0x22, 0x5d,
};
/* y_string_unicode_U+1FFFE_nonchar */
static const unsigned char json_corpus_298[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x44, 0x38, 0x33, 0x46, 0x5c, 0x75, 0x44, 0x46, 0x46, 0x45, 0x22, 0x5d,
};
/* y_string_unicode_U+200B_ZERO_WIDTH_SPACE */
static const unsigned char json_corpus_299[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x32, 0x30, 0x30, 0x42, 0x22, 0x5d,
};
/* y_string_unicode_U+2064_invisible_plus */
static const unsigned char json_corpus_300[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x32, 0x30, 0x36, 0x34, 0x22, 0x5d,
};
/* y_string_unicode_U+FDD0_nonchar */
static const unsigned char json_corpus_301[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x46, 0x44, 0x44, 0x30, 0x22, 0x5d,
};
/* y_string_unicode_U+FFFE_nonchar */
static const unsigned char json_corpus_302[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x46, 0x46, 0x46, 0x45, 0x22, 0x5d,
};
/* y_string_unicode_escaped_double_quote */
static const unsigned char json_corpus_303[] = {
    0x5b, 0x22, 0x5c, 0x75, 0x30, 0x30, 0x32, 0x32, 0x22, 0x5d,
};
/* y_string_utf8 */
static const unsigned char json_corpus_304[] = {
    0x5b, 0x22, 0xe2, 0x82, 0xac, 0xf0, 0x9d, 0x84, 0x9e, 0x22, 0x5d,
};
/* y_string_with_del_character */
static const unsigned char json_corpus_305[] = {
    0x5b, 0x22, 0x61, 0x7f, 0x61, 0x22, 0x5d,
};
/* y_structure_lonely_false */
static const unsigned char json_corpus_306[] = {
    0x66, 0x61, 0x6c, 0x73, 0x65,
};
/* y_structure_lonely_int */
static const unsigned char json_corpus_307[] = {
    0x34, 0x32,
};
/* y_structure_lonely_negative_real */
static const unsigned char json_corpus_308[] = {
    0x2d, 0x30, 0x2e, 0x31,
};
/* y_structure_lonely_null */
static const unsigned char json_corpus_309[] = {
    0x6e, 0x75, 0x6c, 0x6c,
};
/* y_structure_lonely_string */
static const unsigned char json_corpus_310[] = {
    0x22, 0x61, 0x73, 0x64, 0x22,
};
/* y_structure_lonely_true */
static const unsigned char json_corpus_311[] = {
    0x74, 0x72, 0x75, 0x65,
};
/* y_structure_string_empty */
static const unsigned char json_corpus_312[] = {
    0x22, 0x22,
};
/* y_structure_trailing_newline */
static const unsigned char json_corpus_313[] = {
    0x5b, 0x22, 0x61, 0x22, 0x5d, 0x0a,
};
/* y_structure_true_in_array */
static const unsigned char json_corpus_314[] = {
    0x5b, 0x74, 0x72, 0x75, 0x65, 0x5d,
};
/* y_structure_whitespace_array */
static const unsigned char json_corpus_315[] = {
    0x20, 0x5b, 0x5d, 0x20,
};

static const AxlJsonCorpusCase json_corpus[] = {
    { "i_number_double_huge_neg_exp", 'i', json_corpus_000, sizeof(json_corpus_000) },
    { "i_number_huge_exp", 'i', json_corpus_001, sizeof(json_corpus_001) },
    { "i_number_neg_int_huge_exp", 'i', json_corpus_002, sizeof(json_corpus_002) },
    { "i_number_pos_double_huge_exp", 'i', json_corpus_003, sizeof(json_corpus_003) },
    { "i_number_real_neg_overflow", 'i', json_corpus_004, sizeof(json_corpus_004) },
    { "i_number_real_pos_overflow", 'i', json_corpus_005, sizeof(json_corpus_005) },
    { "i_number_real_underflow", 'i', json_corpus_006, sizeof(json_corpus_006) },
    { "i_number_too_big_neg_int", 'i', json_corpus_007, sizeof(json_corpus_007) },
    { "i_number_too_big_pos_int", 'i', json_corpus_008, sizeof(json_corpus_008) },
    { "i_number_very_big_negative_int", 'i', json_corpus_009, sizeof(json_corpus_009) },
    { "i_object_key_lone_2nd_surrogate", 'i', json_corpus_010, sizeof(json_corpus_010) },
    { "i_string_1st_surrogate_but_2nd_missing", 'i', json_corpus_011, sizeof(json_corpus_011) },
    { "i_string_1st_valid_surrogate_2nd_invalid", 'i', json_corpus_012, sizeof(json_corpus_012) },
    { "i_string_UTF-16LE_with_BOM", 'i', json_corpus_013, sizeof(json_corpus_013) },
    { "i_string_UTF-8_invalid_sequence", 'i', json_corpus_014, sizeof(json_corpus_014) },
    { "i_string_UTF8_surrogate_U+D800", 'i', json_corpus_015, sizeof(json_corpus_015) },
    { "i_string_incomplete_surrogate_and_escape_valid", 'i', json_corpus_016, sizeof(json_corpus_016) },
    { "i_string_incomplete_surrogate_pair", 'i', json_corpus_017, sizeof(json_corpus_017) },
    { "i_string_incomplete_surrogates_escape_valid", 'i', json_corpus_018, sizeof(json_corpus_018) },
    { "i_string_invalid_lonely_surrogate", 'i', json_corpus_019, sizeof(json_corpus_019) },
    { "i_string_invalid_surrogate", 'i', json_corpus_020, sizeof(json_corpus_020) },
    { "i_string_invalid_utf-8", 'i', json_corpus_021, sizeof(json_corpus_021) },
    { "i_string_inverted_surrogates_U+1D11E", 'i', json_corpus_022, sizeof(json_corpus_022) },
    { "i_string_iso_latin_1", 'i', json_corpus_023, sizeof(json_corpus_023) },
    { "i_string_lone_second_surrogate", 'i', json_corpus_024, sizeof(json_corpus_024) },
    { "i_string_lone_utf8_continuation_byte", 'i', json_corpus_025, sizeof(json_corpus_025) },
    { "i_string_not_in_unicode_range", 'i', json_corpus_026, sizeof(json_corpus_026) },
    { "i_string_overlong_sequence_2_bytes", 'i', json_corpus_027, sizeof(json_corpus_027) },
    { "i_string_overlong_sequence_6_bytes", 'i', json_corpus_028, sizeof(json_corpus_028) },
    { "i_string_overlong_sequence_6_bytes_null", 'i', json_corpus_029, sizeof(json_corpus_029) },
    { "i_string_truncated-utf-8", 'i', json_corpus_030, sizeof(json_corpus_030) },
    { "i_string_utf16BE_no_BOM", 'i', json_corpus_031, sizeof(json_corpus_031) },
    { "i_string_utf16LE_no_BOM", 'i', json_corpus_032, sizeof(json_corpus_032) },
    { "i_structure_500_nested_arrays", 'i', json_corpus_033, sizeof(json_corpus_033) },
    { "i_structure_UTF-8_BOM_empty_object", 'i', json_corpus_034, sizeof(json_corpus_034) },
    { "n_array_1_true_without_comma", 'n', json_corpus_035, sizeof(json_corpus_035) },
    { "n_array_a_invalid_utf8", 'n', json_corpus_036, sizeof(json_corpus_036) },
    { "n_array_colon_instead_of_comma", 'n', json_corpus_037, sizeof(json_corpus_037) },
    { "n_array_comma_after_close", 'n', json_corpus_038, sizeof(json_corpus_038) },
    { "n_array_comma_and_number", 'n', json_corpus_039, sizeof(json_corpus_039) },
    { "n_array_double_comma", 'n', json_corpus_040, sizeof(json_corpus_040) },
    { "n_array_double_extra_comma", 'n', json_corpus_041, sizeof(json_corpus_041) },
    { "n_array_extra_close", 'n', json_corpus_042, sizeof(json_corpus_042) },
    { "n_array_extra_comma", 'n', json_corpus_043, sizeof(json_corpus_043) },
    { "n_array_incomplete", 'n', json_corpus_044, sizeof(json_corpus_044) },
    { "n_array_incomplete_invalid_value", 'n', json_corpus_045, sizeof(json_corpus_045) },
    { "n_array_inner_array_no_comma", 'n', json_corpus_046, sizeof(json_corpus_046) },
    { "n_array_invalid_utf8", 'n', json_corpus_047, sizeof(json_corpus_047) },
    { "n_array_items_separated_by_semicolon", 'n', json_corpus_048, sizeof(json_corpus_048) },
    { "n_array_just_comma", 'n', json_corpus_049, sizeof(json_corpus_049) },
    { "n_array_just_minus", 'n', json_corpus_050, sizeof(json_corpus_050) },
    { "n_array_missing_value", 'n', json_corpus_051, sizeof(json_corpus_051) },
    { "n_array_newlines_unclosed", 'n', json_corpus_052, sizeof(json_corpus_052) },
    { "n_array_number_and_comma", 'n', json_corpus_053, sizeof(json_corpus_053) },
    { "n_array_number_and_several_commas", 'n', json_corpus_054, sizeof(json_corpus_054) },
    { "n_array_spaces_vertical_tab_formfeed", 'n', json_corpus_055, sizeof(json_corpus_055) },
    { "n_array_star_inside", 'n', json_corpus_056, sizeof(json_corpus_056) },
    { "n_array_unclosed", 'n', json_corpus_057, sizeof(json_corpus_057) },
    { "n_array_unclosed_trailing_comma", 'n', json_corpus_058, sizeof(json_corpus_058) },
    { "n_array_unclosed_with_new_lines", 'n', json_corpus_059, sizeof(json_corpus_059) },
    { "n_array_unclosed_with_object_inside", 'n', json_corpus_060, sizeof(json_corpus_060) },
    { "n_incomplete_false", 'n', json_corpus_061, sizeof(json_corpus_061) },
    { "n_incomplete_null", 'n', json_corpus_062, sizeof(json_corpus_062) },
    { "n_incomplete_true", 'n', json_corpus_063, sizeof(json_corpus_063) },
    { "n_multidigit_number_then_00", 'n', json_corpus_064, sizeof(json_corpus_064) },
    { "n_number_++", 'n', json_corpus_065, sizeof(json_corpus_065) },
    { "n_number_+1", 'n', json_corpus_066, sizeof(json_corpus_066) },
    { "n_number_+Inf", 'n', json_corpus_067, sizeof(json_corpus_067) },
    { "n_number_-01", 'n', json_corpus_068, sizeof(json_corpus_068) },
    { "n_number_-1.0.", 'n', json_corpus_069, sizeof(json_corpus_069) },
    { "n_number_-2.", 'n', json_corpus_070, sizeof(json_corpus_070) },
    { "n_number_-NaN", 'n', json_corpus_071, sizeof(json_corpus_071) },
    { "n_number_.-1", 'n', json_corpus_072, sizeof(json_corpus_072) },
    { "n_number_.2e-3", 'n', json_corpus_073, sizeof(json_corpus_073) },
    { "n_number_0.1.2", 'n', json_corpus_074, sizeof(json_corpus_074) },
    { "n_number_0.3e+", 'n', json_corpus_075, sizeof(json_corpus_075) },
    { "n_number_0.3e", 'n', json_corpus_076, sizeof(json_corpus_076) },
    { "n_number_0.e1", 'n', json_corpus_077, sizeof(json_corpus_077) },
    { "n_number_0_capital_E+", 'n', json_corpus_078, sizeof(json_corpus_078) },
    { "n_number_0_capital_E", 'n', json_corpus_079, sizeof(json_corpus_079) },
    { "n_number_0e+", 'n', json_corpus_080, sizeof(json_corpus_080) },
    { "n_number_0e", 'n', json_corpus_081, sizeof(json_corpus_081) },
    { "n_number_1.0e+", 'n', json_corpus_082, sizeof(json_corpus_082) },
    { "n_number_1.0e-", 'n', json_corpus_083, sizeof(json_corpus_083) },
    { "n_number_1.0e", 'n', json_corpus_084, sizeof(json_corpus_084) },
    { "n_number_1_000", 'n', json_corpus_085, sizeof(json_corpus_085) },
    { "n_number_1eE2", 'n', json_corpus_086, sizeof(json_corpus_086) },
    { "n_number_2.e+3", 'n', json_corpus_087, sizeof(json_corpus_087) },
    { "n_number_2.e-3", 'n', json_corpus_088, sizeof(json_corpus_088) },
    { "n_number_2.e3", 'n', json_corpus_089, sizeof(json_corpus_089) },
    { "n_number_9.e+", 'n', json_corpus_090, sizeof(json_corpus_090) },
    { "n_number_Inf", 'n', json_corpus_091, sizeof(json_corpus_091) },
    { "n_number_NaN", 'n', json_corpus_092, sizeof(json_corpus_092) },
    { "n_number_U+FF11_fullwidth_digit_one", 'n', json_corpus_093, sizeof(json_corpus_093) },
    { "n_number_expression", 'n', json_corpus_094, sizeof(json_corpus_094) },
    { "n_number_hex_1_digit", 'n', json_corpus_095, sizeof(json_corpus_095) },
    { "n_number_hex_2_digits", 'n', json_corpus_096, sizeof(json_corpus_096) },
    { "n_number_infinity", 'n', json_corpus_097, sizeof(json_corpus_097) },
    { "n_number_invalid+-", 'n', json_corpus_098, sizeof(json_corpus_098) },
    { "n_number_invalid-negative-real", 'n', json_corpus_099, sizeof(json_corpus_099) },
    { "n_number_invalid-utf-8-in-bigger-int", 'n', json_corpus_100, sizeof(json_corpus_100) },
    { "n_number_invalid-utf-8-in-exponent", 'n', json_corpus_101, sizeof(json_corpus_101) },
    { "n_number_invalid-utf-8-in-int", 'n', json_corpus_102, sizeof(json_corpus_102) },
    { "n_number_minus_infinity", 'n', json_corpus_103, sizeof(json_corpus_103) },
    { "n_number_minus_sign_with_trailing_garbage", 'n', json_corpus_104, sizeof(json_corpus_104) },
    { "n_number_minus_space_1", 'n', json_corpus_105, sizeof(json_corpus_105) },
    { "n_number_neg_int_starting_with_zero", 'n', json_corpus_106, sizeof(json_corpus_106) },
    { "n_number_neg_real_without_int_part", 'n', json_corpus_107, sizeof(json_corpus_107) },
    { "n_number_neg_with_garbage_at_end", 'n', json_corpus_108, sizeof(json_corpus_108) },
    { "n_number_real_garbage_after_e", 'n', json_corpus_109, sizeof(json_corpus_109) },
    { "n_number_real_with_invalid_utf8_after_e", 'n', json_corpus_110, sizeof(json_corpus_110) },
    { "n_number_real_without_fractional_part", 'n', json_corpus_111, sizeof(json_corpus_111) },
    { "n_number_starting_with_dot", 'n', json_corpus_112, sizeof(json_corpus_112) },
    { "n_number_with_alpha", 'n', json_corpus_113, sizeof(json_corpus_113) },
    { "n_number_with_alpha_char", 'n', json_corpus_114, sizeof(json_corpus_114) },
    { "n_number_with_leading_zero", 'n', json_corpus_115, sizeof(json_corpus_115) },
    { "n_object_bad_value", 'n', json_corpus_116, sizeof(json_corpus_116) },
    { "n_object_bracket_key", 'n', json_corpus_117, sizeof(json_corpus_117) },
    { "n_object_comma_instead_of_colon", 'n', json_corpus_118, sizeof(json_corpus_118) },
    { "n_object_double_colon", 'n', json_corpus_119, sizeof(json_corpus_119) },
    { "n_object_emoji", 'n', json_corpus_120, sizeof(json_corpus_120) },
    { "n_object_garbage_at_end", 'n', json_corpus_121, sizeof(json_corpus_121) },
    { "n_object_key_with_single_quotes", 'n', json_corpus_122, sizeof(json_corpus_122) },
    { "n_object_lone_continuation_byte_in_key_and_trailing_comma", 'n', json_corpus_123, sizeof(json_corpus_123) },
    { "n_object_missing_colon", 'n', json_corpus_124, sizeof(json_corpus_124) },
    { "n_object_missing_key", 'n', json_corpus_125, sizeof(json_corpus_125) },
    { "n_object_missing_semicolon", 'n', json_corpus_126, sizeof(json_corpus_126) },
    { "n_object_missing_value", 'n', json_corpus_127, sizeof(json_corpus_127) },
    { "n_object_no-colon", 'n', json_corpus_128, sizeof(json_corpus_128) },
    { "n_object_non_string_key", 'n', json_corpus_129, sizeof(json_corpus_129) },
    { "n_object_non_string_key_but_huge_number_instead", 'n', json_corpus_130, sizeof(json_corpus_130) },
    { "n_object_repeated_null_null", 'n', json_corpus_131, sizeof(json_corpus_131) },
    { "n_object_several_trailing_commas", 'n', json_corpus_132, sizeof(json_corpus_132) },
    { "n_object_single_quote", 'n', json_corpus_133, sizeof(json_corpus_133) },
    { "n_object_trailing_comma", 'n', json_corpus_134, sizeof(json_corpus_134) },
    { "n_object_trailing_comment", 'n', json_corpus_135, sizeof(json_corpus_135) },
    { "n_object_trailing_comment_open", 'n', json_corpus_136, sizeof(json_corpus_136) },
    { "n_object_trailing_comment_slash_open", 'n', json_corpus_137, sizeof(json_corpus_137) },
    { "n_object_trailing_comment_slash_open_incomplete", 'n', json_corpus_138, sizeof(json_corpus_138) },
    { "n_object_two_commas_in_a_row", 'n', json_corpus_139, sizeof(json_corpus_139) },
    { "n_object_unquoted_key", 'n', json_corpus_140, sizeof(json_corpus_140) },
    { "n_object_unterminated-value", 'n', json_corpus_141, sizeof(json_corpus_141) },
    { "n_object_with_single_string", 'n', json_corpus_142, sizeof(json_corpus_142) },
    { "n_object_with_trailing_garbage", 'n', json_corpus_143, sizeof(json_corpus_143) },
    { "n_single_space", 'n', json_corpus_144, sizeof(json_corpus_144) },
    { "n_string_1_surrogate_then_escape", 'n', json_corpus_145, sizeof(json_corpus_145) },
    { "n_string_1_surrogate_then_escape_u", 'n', json_corpus_146, sizeof(json_corpus_146) },
    { "n_string_1_surrogate_then_escape_u1", 'n', json_corpus_147, sizeof(json_corpus_147) },
    { "n_string_1_surrogate_then_escape_u1x", 'n', json_corpus_148, sizeof(json_corpus_148) },
    { "n_string_accentuated_char_no_quotes", 'n', json_corpus_149, sizeof(json_corpus_149) },
    { "n_string_backslash_00", 'n', json_corpus_150, sizeof(json_corpus_150) },
    { "n_string_escape_x", 'n', json_corpus_151, sizeof(json_corpus_151) },
    { "n_string_escaped_backslash_bad", 'n', json_corpus_152, sizeof(json_corpus_152) },
    { "n_string_escaped_ctrl_char_tab", 'n', json_corpus_153, sizeof(json_corpus_153) },
    { "n_string_escaped_emoji", 'n', json_corpus_154, sizeof(json_corpus_154) },
    { "n_string_incomplete_escape", 'n', json_corpus_155, sizeof(json_corpus_155) },
    { "n_string_incomplete_escaped_character", 'n', json_corpus_156, sizeof(json_corpus_156) },
    { "n_string_incomplete_surrogate", 'n', json_corpus_157, sizeof(json_corpus_157) },
    { "n_string_incomplete_surrogate_escape_invalid", 'n', json_corpus_158, sizeof(json_corpus_158) },
    { "n_string_invalid-utf-8-in-escape", 'n', json_corpus_159, sizeof(json_corpus_159) },
    { "n_string_invalid_backslash_esc", 'n', json_corpus_160, sizeof(json_corpus_160) },
    { "n_string_invalid_unicode_escape", 'n', json_corpus_161, sizeof(json_corpus_161) },
    { "n_string_invalid_utf8_after_escape", 'n', json_corpus_162, sizeof(json_corpus_162) },
    { "n_string_leading_uescaped_thinspace", 'n', json_corpus_163, sizeof(json_corpus_163) },
    { "n_string_no_quotes_with_bad_escape", 'n', json_corpus_164, sizeof(json_corpus_164) },
    { "n_string_single_doublequote", 'n', json_corpus_165, sizeof(json_corpus_165) },
    { "n_string_single_quote", 'n', json_corpus_166, sizeof(json_corpus_166) },
    { "n_string_single_string_no_double_quotes", 'n', json_corpus_167, sizeof(json_corpus_167) },
    { "n_string_start_escape_unclosed", 'n', json_corpus_168, sizeof(json_corpus_168) },
    { "n_string_unescaped_ctrl_char", 'n', json_corpus_169, sizeof(json_corpus_169) },
    { "n_string_unescaped_newline", 'n', json_corpus_170, sizeof(json_corpus_170) },
    { "n_string_unescaped_tab", 'n', json_corpus_171, sizeof(json_corpus_171) },
    { "n_string_unicode_CapitalU", 'n', json_corpus_172, sizeof(json_corpus_172) },
    { "n_string_with_trailing_garbage", 'n', json_corpus_173, sizeof(json_corpus_173) },
    { "n_structure_U+2060_word_joined", 'n', json_corpus_174, sizeof(json_corpus_174) },
    { "n_structure_UTF8_BOM_no_data", 'n', json_corpus_175, sizeof(json_corpus_175) },
    { "n_structure_angle_bracket_.", 'n', json_corpus_176, sizeof(json_corpus_176) },
    { "n_structure_angle_bracket_null", 'n', json_corpus_177, sizeof(json_corpus_177) },
    { "n_structure_array_trailing_garbage", 'n', json_corpus_178, sizeof(json_corpus_178) },
    { "n_structure_array_with_extra_array_close", 'n', json_corpus_179, sizeof(json_corpus_179) },
    { "n_structure_array_with_unclosed_string", 'n', json_corpus_180, sizeof(json_corpus_180) },
    { "n_structure_ascii-unicode-identifier", 'n', json_corpus_181, sizeof(json_corpus_181) },
    { "n_structure_capitalized_True", 'n', json_corpus_182, sizeof(json_corpus_182) },
    { "n_structure_close_unopened_array", 'n', json_corpus_183, sizeof(json_corpus_183) },
    { "n_structure_comma_instead_of_closing_brace", 'n', json_corpus_184, sizeof(json_corpus_184) },
    { "n_structure_double_array", 'n', json_corpus_185, sizeof(json_corpus_185) },
    { "n_structure_end_array", 'n', json_corpus_186, sizeof(json_corpus_186) },
    { "n_structure_incomplete_UTF8_BOM", 'n', json_corpus_187, sizeof(json_corpus_187) },
    { "n_structure_lone-invalid-utf-8", 'n', json_corpus_188, sizeof(json_corpus_188) },
    { "n_structure_lone-open-bracket", 'n', json_corpus_189, sizeof(json_corpus_189) },
    { "n_structure_no_data", 'n', json_corpus_190, sizeof(json_corpus_190) },
    { "n_structure_null-byte-outside-string", 'n', json_corpus_191, sizeof(json_corpus_191) },
    { "n_structure_number_with_trailing_garbage", 'n', json_corpus_192, sizeof(json_corpus_192) },
    { "n_structure_object_followed_by_closing_object", 'n', json_corpus_193, sizeof(json_corpus_193) },
    { "n_structure_object_unclosed_no_value", 'n', json_corpus_194, sizeof(json_corpus_194) },
    { "n_structure_object_with_comment", 'n', json_corpus_195, sizeof(json_corpus_195) },
    { "n_structure_object_with_trailing_garbage", 'n', json_corpus_196, sizeof(json_corpus_196) },
    { "n_structure_open_array_apostrophe", 'n', json_corpus_197, sizeof(json_corpus_197) },
    { "n_structure_open_array_comma", 'n', json_corpus_198, sizeof(json_corpus_198) },
    { "n_structure_open_array_open_object", 'n', json_corpus_199, sizeof(json_corpus_199) },
    { "n_structure_open_array_open_string", 'n', json_corpus_200, sizeof(json_corpus_200) },
    { "n_structure_open_array_string", 'n', json_corpus_201, sizeof(json_corpus_201) },
    { "n_structure_open_object", 'n', json_corpus_202, sizeof(json_corpus_202) },
    { "n_structure_open_object_close_array", 'n', json_corpus_203, sizeof(json_corpus_203) },
    { "n_structure_open_object_comma", 'n', json_corpus_204, sizeof(json_corpus_204) },
    { "n_structure_open_object_open_array", 'n', json_corpus_205, sizeof(json_corpus_205) },
    { "n_structure_open_object_open_string", 'n', json_corpus_206, sizeof(json_corpus_206) },
    { "n_structure_open_object_string_with_apostrophes", 'n', json_corpus_207, sizeof(json_corpus_207) },
    { "n_structure_open_open", 'n', json_corpus_208, sizeof(json_corpus_208) },
    { "n_structure_single_eacute", 'n', json_corpus_209, sizeof(json_corpus_209) },
    { "n_structure_single_star", 'n', json_corpus_210, sizeof(json_corpus_210) },
    { "n_structure_trailing_#", 'n', json_corpus_211, sizeof(json_corpus_211) },
    { "n_structure_uescaped_LF_before_string", 'n', json_corpus_212, sizeof(json_corpus_212) },
    { "n_structure_unclosed_array", 'n', json_corpus_213, sizeof(json_corpus_213) },
    { "n_structure_unclosed_array_partial_null", 'n', json_corpus_214, sizeof(json_corpus_214) },
    { "n_structure_unclosed_array_unfinished_false", 'n', json_corpus_215, sizeof(json_corpus_215) },
    { "n_structure_unclosed_array_unfinished_true", 'n', json_corpus_216, sizeof(json_corpus_216) },
    { "n_structure_unclosed_object", 'n', json_corpus_217, sizeof(json_corpus_217) },
    { "n_structure_unicode-identifier", 'n', json_corpus_218, sizeof(json_corpus_218) },
    { "n_structure_whitespace_U+2060_word_joiner", 'n', json_corpus_219, sizeof(json_corpus_219) },
    { "n_structure_whitespace_formfeed", 'n', json_corpus_220, sizeof(json_corpus_220) },
    { "y_array_arraysWithSpaces", 'y', json_corpus_221, sizeof(json_corpus_221) },
    { "y_array_empty-string", 'y', json_corpus_222, sizeof(json_corpus_222) },
    { "y_array_empty", 'y', json_corpus_223, sizeof(json_corpus_223) },
    { "y_array_ending_with_newline", 'y', json_corpus_224, sizeof(json_corpus_224) },
    { "y_array_false", 'y', json_corpus_225, sizeof(json_corpus_225) },
    { "y_array_heterogeneous", 'y', json_corpus_226, sizeof(json_corpus_226) },
    { "y_array_null", 'y', json_corpus_227, sizeof(json_corpus_227) },
    { "y_array_with_1_and_newline", 'y', json_corpus_228, sizeof(json_corpus_228) },
    { "y_array_with_leading_space", 'y', json_corpus_229, sizeof(json_corpus_229) },
    { "y_array_with_several_null", 'y', json_corpus_230, sizeof(json_corpus_230) },
    { "y_array_with_trailing_space", 'y', json_corpus_231, sizeof(json_corpus_231) },
    { "y_number", 'y', json_corpus_232, sizeof(json_corpus_232) },
    { "y_number_0e+1", 'y', json_corpus_233, sizeof(json_corpus_233) },
    { "y_number_0e1", 'y', json_corpus_234, sizeof(json_corpus_234) },
    { "y_number_after_space", 'y', json_corpus_235, sizeof(json_corpus_235) },
    { "y_number_double_close_to_zero", 'y', json_corpus_236, sizeof(json_corpus_236) },
    { "y_number_int_with_exp", 'y', json_corpus_237, sizeof(json_corpus_237) },
    { "y_number_minus_zero", 'y', json_corpus_238, sizeof(json_corpus_238) },
    { "y_number_negative_int", 'y', json_corpus_239, sizeof(json_corpus_239) },
    { "y_number_negative_one", 'y', json_corpus_240, sizeof(json_corpus_240) },
    { "y_number_negative_zero", 'y', json_corpus_241, sizeof(json_corpus_241) },
    { "y_number_real_capital_e", 'y', json_corpus_242, sizeof(json_corpus_242) },
    { "y_number_real_capital_e_neg_exp", 'y', json_corpus_243, sizeof(json_corpus_243) },
    { "y_number_real_capital_e_pos_exp", 'y', json_corpus_244, sizeof(json_corpus_244) },
    { "y_number_real_exponent", 'y', json_corpus_245, sizeof(json_corpus_245) },
    { "y_number_real_fraction_exponent", 'y', json_corpus_246, sizeof(json_corpus_246) },
    { "y_number_real_neg_exp", 'y', json_corpus_247, sizeof(json_corpus_247) },
    { "y_number_real_pos_exponent", 'y', json_corpus_248, sizeof(json_corpus_248) },
    { "y_number_simple_int", 'y', json_corpus_249, sizeof(json_corpus_249) },
    { "y_number_simple_real", 'y', json_corpus_250, sizeof(json_corpus_250) },
    { "y_object", 'y', json_corpus_251, sizeof(json_corpus_251) },
    { "y_object_basic", 'y', json_corpus_252, sizeof(json_corpus_252) },
    { "y_object_duplicated_key", 'y', json_corpus_253, sizeof(json_corpus_253) },
    { "y_object_duplicated_key_and_value", 'y', json_corpus_254, sizeof(json_corpus_254) },
    { "y_object_empty", 'y', json_corpus_255, sizeof(json_corpus_255) },
    { "y_object_empty_key", 'y', json_corpus_256, sizeof(json_corpus_256) },
    { "y_object_escaped_null_in_key", 'y', json_corpus_257, sizeof(json_corpus_257) },
    { "y_object_extreme_numbers", 'y', json_corpus_258, sizeof(json_corpus_258) },
    { "y_object_long_strings", 'y', json_corpus_259, sizeof(json_corpus_259) },
    { "y_object_simple", 'y', json_corpus_260, sizeof(json_corpus_260) },
    { "y_object_string_unicode", 'y', json_corpus_261, sizeof(json_corpus_261) },
    { "y_object_with_newlines", 'y', json_corpus_262, sizeof(json_corpus_262) },
    { "y_string_1_2_3_bytes_UTF-8_sequences", 'y', json_corpus_263, sizeof(json_corpus_263) },
    { "y_string_accepted_surrogate_pair", 'y', json_corpus_264, sizeof(json_corpus_264) },
    { "y_string_accepted_surrogate_pairs", 'y', json_corpus_265, sizeof(json_corpus_265) },
    { "y_string_allowed_escapes", 'y', json_corpus_266, sizeof(json_corpus_266) },
    { "y_string_backslash_and_u_escaped_zero", 'y', json_corpus_267, sizeof(json_corpus_267) },
    { "y_string_backslash_doublequotes", 'y', json_corpus_268, sizeof(json_corpus_268) },
    { "y_string_comments", 'y', json_corpus_269, sizeof(json_corpus_269) },
    { "y_string_double_escape_a", 'y', json_corpus_270, sizeof(json_corpus_270) },
    { "y_string_double_escape_n", 'y', json_corpus_271, sizeof(json_corpus_271) },
    { "y_string_escaped_control_character", 'y', json_corpus_272, sizeof(json_corpus_272) },
    { "y_string_escaped_noncharacter", 'y', json_corpus_273, sizeof(json_corpus_273) },
    { "y_string_in_array", 'y', json_corpus_274, sizeof(json_corpus_274) },
    { "y_string_in_array_with_leading_space", 'y', json_corpus_275, sizeof(json_corpus_275) },
    { "y_string_last_surrogates_1_and_2", 'y', json_corpus_276, sizeof(json_corpus_276) },
    { "y_string_nbsp_uescaped", 'y', json_corpus_277, sizeof(json_corpus_277) },
    { "y_string_nonCharacterInUTF-8_U+10FFFF", 'y', json_corpus_278, sizeof(json_corpus_278) },
    { "y_string_nonCharacterInUTF-8_U+FFFF", 'y', json_corpus_279, sizeof(json_corpus_279) },
    { "y_string_null_escape", 'y', json_corpus_280, sizeof(json_corpus_280) },
    { "y_string_one-byte-utf-8", 'y', json_corpus_281, sizeof(json_corpus_281) },
    { "y_string_pi", 'y', json_corpus_282, sizeof(json_corpus_282) },
    { "y_string_reservedCharacterInUTF-8_U+1BFFF", 'y', json_corpus_283, sizeof(json_corpus_283) },
    { "y_string_simple_ascii", 'y', json_corpus_284, sizeof(json_corpus_284) },
    { "y_string_space", 'y', json_corpus_285, sizeof(json_corpus_285) },
    { "y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF", 'y', json_corpus_286, sizeof(json_corpus_286) },
    { "y_string_three-byte-utf-8", 'y', json_corpus_287, sizeof(json_corpus_287) },
    { "y_string_two-byte-utf-8", 'y', json_corpus_288, sizeof(json_corpus_288) },
    { "y_string_u+2028_line_sep", 'y', json_corpus_289, sizeof(json_corpus_289) },
    { "y_string_u+2029_par_sep", 'y', json_corpus_290, sizeof(json_corpus_290) },
    { "y_string_uEscape", 'y', json_corpus_291, sizeof(json_corpus_291) },
    { "y_string_uescaped_newline", 'y', json_corpus_292, sizeof(json_corpus_292) },
    { "y_string_unescaped_char_delete", 'y', json_corpus_293, sizeof(json_corpus_293) },
    { "y_string_unicode", 'y', json_corpus_294, sizeof(json_corpus_294) },
    { "y_string_unicodeEscapedBackslash", 'y', json_corpus_295, sizeof(json_corpus_295) },
    { "y_string_unicode_2", 'y', json_corpus_296, sizeof(json_corpus_296) },
    { "y_string_unicode_U+10FFFE_nonchar", 'y', json_corpus_297, sizeof(json_corpus_297) },
    { "y_string_unicode_U+1FFFE_nonchar", 'y', json_corpus_298, sizeof(json_corpus_298) },
    { "y_string_unicode_U+200B_ZERO_WIDTH_SPACE", 'y', json_corpus_299, sizeof(json_corpus_299) },
    { "y_string_unicode_U+2064_invisible_plus", 'y', json_corpus_300, sizeof(json_corpus_300) },
    { "y_string_unicode_U+FDD0_nonchar", 'y', json_corpus_301, sizeof(json_corpus_301) },
    { "y_string_unicode_U+FFFE_nonchar", 'y', json_corpus_302, sizeof(json_corpus_302) },
    { "y_string_unicode_escaped_double_quote", 'y', json_corpus_303, sizeof(json_corpus_303) },
    { "y_string_utf8", 'y', json_corpus_304, sizeof(json_corpus_304) },
    { "y_string_with_del_character", 'y', json_corpus_305, sizeof(json_corpus_305) },
    { "y_structure_lonely_false", 'y', json_corpus_306, sizeof(json_corpus_306) },
    { "y_structure_lonely_int", 'y', json_corpus_307, sizeof(json_corpus_307) },
    { "y_structure_lonely_negative_real", 'y', json_corpus_308, sizeof(json_corpus_308) },
    { "y_structure_lonely_null", 'y', json_corpus_309, sizeof(json_corpus_309) },
    { "y_structure_lonely_string", 'y', json_corpus_310, sizeof(json_corpus_310) },
    { "y_structure_lonely_true", 'y', json_corpus_311, sizeof(json_corpus_311) },
    { "y_structure_string_empty", 'y', json_corpus_312, sizeof(json_corpus_312) },
    { "y_structure_trailing_newline", 'y', json_corpus_313, sizeof(json_corpus_313) },
    { "y_structure_true_in_array", 'y', json_corpus_314, sizeof(json_corpus_314) },
    { "y_structure_whitespace_array", 'y', json_corpus_315, sizeof(json_corpus_315) },
};

/** Cases HELD BACK as oversize, by name.
 *
 * A checkable table, not just the prose in the file comment above:
 * the test matches every name here against the documents it rebuilds
 * at runtime, so a corpus case that grows past the size threshold
 * cannot quietly drop out of the sweep. Growing this list has to be
 * a deliberate act with a matching reconstruction. */
static const char *const json_corpus_skipped[] = {
    "n_structure_100000_opening_arrays",
    "n_structure_open_array_object",
};

/// Number of held-back cases the test must rebuild itself.
#define AXL_JSON_CORPUS_SKIPPED_COUNT 2

/// Number of embedded conformance cases.
#define AXL_JSON_CORPUS_COUNT (sizeof(json_corpus) / sizeof(json_corpus[0]))

/** @name Embedded case counts per class
 *
 * Spelled out so a corpus regeneration that changes the mix is a
 * visible diff in the assertions, not a silently different total.
 * @{ */
#define AXL_JSON_CORPUS_Y_COUNT 95
#define AXL_JSON_CORPUS_N_COUNT 186
#define AXL_JSON_CORPUS_I_COUNT 35
/** @} */

#endif /* AXL_JSON_CORPUS_H */
